/*
 * This file is generated by jOOQ.
*/
package com.ebupt.admin.database.tables;


import com.ebupt.admin.database.Indexes;
import com.ebupt.admin.database.Keys;
import com.ebupt.admin.database.St;
import com.ebupt.admin.database.tables.records.BusinessCwRecoardRecord;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BusinessCwRecoard extends TableImpl<BusinessCwRecoardRecord> {

    private static final long serialVersionUID = 1825618959;

    /**
     * The reference instance of <code>st.business_cw_recoard</code>
     */
    public static final BusinessCwRecoard BUSINESS_CW_RECOARD = new BusinessCwRecoard();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BusinessCwRecoardRecord> getRecordType() {
        return BusinessCwRecoardRecord.class;
    }

    /**
     * The column <code>st.business_cw_recoard.statistics_time</code>. 对账日期
     */
    public final TableField<BusinessCwRecoardRecord, String> STATISTICS_TIME = createField("statistics_time", org.jooq.impl.SQLDataType.VARCHAR(255), this, "对账日期");

    /**
     * The column <code>st.business_cw_recoard.business_id</code>.
     */
    public final TableField<BusinessCwRecoardRecord, Integer> BUSINESS_ID = createField("business_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>st.business_cw_recoard.line_code</code>.
     */
    public final TableField<BusinessCwRecoardRecord, String> LINE_CODE = createField("line_code", org.jooq.impl.SQLDataType.VARCHAR(10).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>st.business_cw_recoard.yf_hfsyyf</code>. 运费对账——返还剩余运费
     */
    public final TableField<BusinessCwRecoardRecord, String> YF_HFSYYF = createField("yf_hfsyyf", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "运费对账——返还剩余运费");

    /**
     * The column <code>st.business_cw_recoard.hldf</code>.
     */
    public final TableField<BusinessCwRecoardRecord, String> HLDF = createField("hldf", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>st.business_cw_recoard.rb_qc_ps</code>. 日报表——期初结余——票数
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_QC_PS = createField("rb_qc_ps", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "日报表——期初结余——票数");

    /**
     * The column <code>st.business_cw_recoard.rb_bq_ps</code>. 日报表——本期到货——票数
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_BQ_PS = createField("rb_bq_ps", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "日报表——本期到货——票数");

    /**
     * The column <code>st.business_cw_recoard.rb_xj_ps</code>. 日报表——小计——票数
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_XJ_PS = createField("rb_xj_ps", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "日报表——小计——票数");

    /**
     * The column <code>st.business_cw_recoard.rb_qm_ps</code>. 日报表——期末结余——票数
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_QM_PS = createField("rb_qm_ps", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "日报表——期末结余——票数");

    /**
     * The column <code>st.business_cw_recoard.ycps</code>.
     */
    public final TableField<BusinessCwRecoardRecord, String> YCPS = createField("ycps", org.jooq.impl.SQLDataType.VARCHAR(50).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>st.business_cw_recoard.ycbz</code>.
     */
    public final TableField<BusinessCwRecoardRecord, String> YCBZ = createField("ycbz", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>st.business_cw_recoard.ycdfk</code>. å¼‚å¸¸åž«ä»˜æ¬¾
     */
    public final TableField<BusinessCwRecoardRecord, String> YCDFK = createField("ycdfk", org.jooq.impl.SQLDataType.VARCHAR(50).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "å¼‚å¸¸åž«ä»˜æ¬¾");

    /**
     * The column <code>st.business_cw_recoard.ycdsk</code>. å¼‚å¸¸ä»£æ”¶æ¬¾
     */
    public final TableField<BusinessCwRecoardRecord, String> YCDSK = createField("ycdsk", org.jooq.impl.SQLDataType.VARCHAR(50).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "å¼‚å¸¸ä»£æ”¶æ¬¾");

    /**
     * The column <code>st.business_cw_recoard.ycyf</code>. 常异运费
     */
    public final TableField<BusinessCwRecoardRecord, String> YCYF = createField("ycyf", org.jooq.impl.SQLDataType.VARCHAR(50).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "常异运费");

    /**
     * The column <code>st.business_cw_recoard.ycje</code>. 异常金额
     */
    public final TableField<BusinessCwRecoardRecord, String> YCJE = createField("ycje", org.jooq.impl.SQLDataType.VARCHAR(50).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "异常金额");

    /**
     * The column <code>st.business_cw_recoard.yf_sjyf5</code>.
     */
    public final TableField<BusinessCwRecoardRecord, String> YF_SJYF5 = createField("yf_sjyf5", org.jooq.impl.SQLDataType.VARCHAR(50).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>st.business_cw_recoard.yf_sjyf4</code>.
     */
    public final TableField<BusinessCwRecoardRecord, String> YF_SJYF4 = createField("yf_sjyf4", org.jooq.impl.SQLDataType.VARCHAR(50).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>st.business_cw_recoard.yf_sjyf3</code>.
     */
    public final TableField<BusinessCwRecoardRecord, String> YF_SJYF3 = createField("yf_sjyf3", org.jooq.impl.SQLDataType.VARCHAR(50).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>st.business_cw_recoard.dsk_yc</code>.
     */
    public final TableField<BusinessCwRecoardRecord, String> DSK_YC = createField("dsk_yc", org.jooq.impl.SQLDataType.VARCHAR(50).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>st.business_cw_recoard.dfk_yc</code>.
     */
    public final TableField<BusinessCwRecoardRecord, String> DFK_YC = createField("dfk_yc", org.jooq.impl.SQLDataType.VARCHAR(50).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>st.business_cw_recoard.yf_yc</code>.
     */
    public final TableField<BusinessCwRecoardRecord, String> YF_YC = createField("yf_yc", org.jooq.impl.SQLDataType.VARCHAR(50).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>st.business_cw_recoard.id</code>.
     */
    public final TableField<BusinessCwRecoardRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>st.business_cw_recoard.ticketor</code>.
     */
    public final TableField<BusinessCwRecoardRecord, String> TICKETOR = createField("ticketor", org.jooq.impl.SQLDataType.VARCHAR(11), this, "");

    /**
     * The column <code>st.business_cw_recoard.rb_qc_je</code>. 日报表——期初结余——金额
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_QC_JE = createField("rb_qc_je", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "日报表——期初结余——金额");

    /**
     * The column <code>st.business_cw_recoard.rb_qc_yf</code>. 日报表——期初结余——运费
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_QC_YF = createField("rb_qc_yf", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "日报表——期初结余——运费");

    /**
     * The column <code>st.business_cw_recoard.rb_qc_dshk</code>. 日报表——期初结余——代收货款
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_QC_DSHK = createField("rb_qc_dshk", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "日报表——期初结余——代收货款");

    /**
     * The column <code>st.business_cw_recoard.rb_qc_dfk</code>. 日报表——期初结余——垫付款
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_QC_DFK = createField("rb_qc_dfk", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "日报表——期初结余——垫付款");

    /**
     * The column <code>st.business_cw_recoard.rb_bq_je</code>. 日报表——本期到货——金额
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_BQ_JE = createField("rb_bq_je", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "日报表——本期到货——金额");

    /**
     * The column <code>st.business_cw_recoard.rb_bq_yf</code>. 日报表——本期到货——运费
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_BQ_YF = createField("rb_bq_yf", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "日报表——本期到货——运费");

    /**
     * The column <code>st.business_cw_recoard.rb_bq_dshk</code>. 日报表——本期到货——代收货款
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_BQ_DSHK = createField("rb_bq_dshk", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "日报表——本期到货——代收货款");

    /**
     * The column <code>st.business_cw_recoard.rb_bq_dfk</code>. 日报表——本期到货——垫付款
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_BQ_DFK = createField("rb_bq_dfk", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "日报表——本期到货——垫付款");

    /**
     * The column <code>st.business_cw_recoard.rb_xj_je</code>. 日报表——小计——金额
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_XJ_JE = createField("rb_xj_je", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "日报表——小计——金额");

    /**
     * The column <code>st.business_cw_recoard.rb_xj_yf</code>. 日报表——小计——运费
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_XJ_YF = createField("rb_xj_yf", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "日报表——小计——运费");

    /**
     * The column <code>st.business_cw_recoard.rb_xj_dshk</code>. 日报表——小计——代收货款
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_XJ_DSHK = createField("rb_xj_dshk", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "日报表——小计——代收货款");

    /**
     * The column <code>st.business_cw_recoard.rb_xj_dfk</code>. 日报表——小计——垫付款
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_XJ_DFK = createField("rb_xj_dfk", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "日报表——小计——垫付款");

    /**
     * The column <code>st.business_cw_recoard.rb_tf_ps</code>. 日报表——提付——票数
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_TF_PS = createField("rb_tf_ps", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "日报表——提付——票数");

    /**
     * The column <code>st.business_cw_recoard.rb_tf_je</code>. 日报表——提付——金额
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_TF_JE = createField("rb_tf_je", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "日报表——提付——金额");

    /**
     * The column <code>st.business_cw_recoard.rb_tf_yf</code>. 日报表——提付——运费
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_TF_YF = createField("rb_tf_yf", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "日报表——提付——运费");

    /**
     * The column <code>st.business_cw_recoard.rb_tf_dshk</code>. 日报表——提付——代收货款
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_TF_DSHK = createField("rb_tf_dshk", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "日报表——提付——代收货款");

    /**
     * The column <code>st.business_cw_recoard.rb_tf_dfk</code>. 日报表——提付——垫付款
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_TF_DFK = createField("rb_tf_dfk", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "日报表——提付——垫付款");

    /**
     * The column <code>st.business_cw_recoard.rb_xf_ps</code>. 日报表——现付——票数
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_XF_PS = createField("rb_xf_ps", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "日报表——现付——票数");

    /**
     * The column <code>st.business_cw_recoard.rb_xf_je</code>. 日报表——现付——金额
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_XF_JE = createField("rb_xf_je", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "日报表——现付——金额");

    /**
     * The column <code>st.business_cw_recoard.rb_xf_yf</code>. 日报表——现付——运费
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_XF_YF = createField("rb_xf_yf", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "日报表——现付——运费");

    /**
     * The column <code>st.business_cw_recoard.rb_xf_dshk</code>. 日报表——现付——代收货款
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_XF_DSHK = createField("rb_xf_dshk", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "日报表——现付——代收货款");

    /**
     * The column <code>st.business_cw_recoard.rb_xf_dfk</code>. 日报表——现付——垫付款
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_XF_DFK = createField("rb_xf_dfk", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "日报表——现付——垫付款");

    /**
     * The column <code>st.business_cw_recoard.rb_fhd_ps</code>. 日报表——返单,回单——票数
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_FHD_PS = createField("rb_fhd_ps", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "日报表——返单,回单——票数");

    /**
     * The column <code>st.business_cw_recoard.rb_fhd_je</code>. 日报表——返单,回单——金额
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_FHD_JE = createField("rb_fhd_je", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "日报表——返单,回单——金额");

    /**
     * The column <code>st.business_cw_recoard.rb_fhd_yf</code>. 日报表——返单,回单——运费
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_FHD_YF = createField("rb_fhd_yf", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "日报表——返单,回单——运费");

    /**
     * The column <code>st.business_cw_recoard.rb_fhd_dshk</code>. 日报表——返单,回单——代收货款
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_FHD_DSHK = createField("rb_fhd_dshk", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "日报表——返单,回单——代收货款");

    /**
     * The column <code>st.business_cw_recoard.rb_fhd_dfk</code>. 日报表——返单,回单——垫付款
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_FHD_DFK = createField("rb_fhd_dfk", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "日报表——返单,回单——垫付款");

    /**
     * The column <code>st.business_cw_recoard.rb_yc_ps</code>. 日报表——异常处理——票数
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_YC_PS = createField("rb_yc_ps", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "日报表——异常处理——票数");

    /**
     * The column <code>st.business_cw_recoard.rb_yc_je</code>. 日报表——异常处理——金额
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_YC_JE = createField("rb_yc_je", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "日报表——异常处理——金额");

    /**
     * The column <code>st.business_cw_recoard.rb_yc_yf</code>. 日报表——异常处理——运费
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_YC_YF = createField("rb_yc_yf", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "日报表——异常处理——运费");

    /**
     * The column <code>st.business_cw_recoard.rb_yc_dshk</code>. 日报表——异常处理——代收货款
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_YC_DSHK = createField("rb_yc_dshk", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "日报表——异常处理——代收货款");

    /**
     * The column <code>st.business_cw_recoard.rb_yc_dfk</code>. 日报表——异常处理——垫付款
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_YC_DFK = createField("rb_yc_dfk", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "日报表——异常处理——垫付款");

    /**
     * The column <code>st.business_cw_recoard.rb_qm_je</code>. 日报表——期末结余——金额
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_QM_JE = createField("rb_qm_je", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "日报表——期末结余——金额");

    /**
     * The column <code>st.business_cw_recoard.rb_qm_yf</code>. 日报表——期末结余——运费
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_QM_YF = createField("rb_qm_yf", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "日报表——期末结余——运费");

    /**
     * The column <code>st.business_cw_recoard.rb_qm_dshk</code>. 日报表——期末结余——代收货款
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_QM_DSHK = createField("rb_qm_dshk", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "日报表——期末结余——代收货款");

    /**
     * The column <code>st.business_cw_recoard.rb_qm_dfk</code>. 日报表——期末结余——垫付款
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_QM_DFK = createField("rb_qm_dfk", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "日报表——期末结余——垫付款");

    /**
     * The column <code>st.business_cw_recoard.dsk_ssdsk</code>. 代收款对账——实收代收款
     */
    public final TableField<BusinessCwRecoardRecord, String> DSK_SSDSK = createField("dsk_ssdsk", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "代收款对账——实收代收款");

    /**
     * The column <code>st.business_cw_recoard.dsk_dsksxf</code>. 代收款对账——代收款手续费
     */
    public final TableField<BusinessCwRecoardRecord, String> DSK_DSKSXF = createField("dsk_dsksxf", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "代收款对账——代收款手续费");

    /**
     * The column <code>st.business_cw_recoard.dsk_fhdsk</code>. 代收款对账——返还代收款
     */
    public final TableField<BusinessCwRecoardRecord, String> DSK_FHDSK = createField("dsk_fhdsk", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "代收款对账——返还代收款");

    /**
     * The column <code>st.business_cw_recoard.dsk_ssdfk</code>. 代收款对账——实收垫付款
     */
    public final TableField<BusinessCwRecoardRecord, String> DSK_SSDFK = createField("dsk_ssdfk", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "代收款对账——实收垫付款");

    /**
     * The column <code>st.business_cw_recoard.dsk_dfksxf</code>. 代收款对账——垫付款手续费
     */
    public final TableField<BusinessCwRecoardRecord, String> DSK_DFKSXF = createField("dsk_dfksxf", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "代收款对账——垫付款手续费");

    /**
     * The column <code>st.business_cw_recoard.dsk_fhdfk</code>. 代收款对账——返还垫付款
     */
    public final TableField<BusinessCwRecoardRecord, String> DSK_FHDFK = createField("dsk_fhdfk", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "代收款对账——返还垫付款");

    /**
     * The column <code>st.business_cw_recoard.dsk_fhhj</code>. 代收款对账——返还合计
     */
    public final TableField<BusinessCwRecoardRecord, String> DSK_FHHJ = createField("dsk_fhhj", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "代收款对账——返还合计");

    /**
     * The column <code>st.business_cw_recoard.yf_ssyf</code>. 运费对账——实收运费
     */
    public final TableField<BusinessCwRecoardRecord, String> YF_SSYF = createField("yf_ssyf", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "运费对账——实收运费");

    /**
     * The column <code>st.business_cw_recoard.yf_drdhyfze</code>. 运费对账——当日到货运费总额
     */
    public final TableField<BusinessCwRecoardRecord, String> YF_DRDHYFZE = createField("yf_drdhyfze", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "运费对账——当日到货运费总额");

    /**
     * The column <code>st.business_cw_recoard.yf_sxfxf</code>. 运费对账——运费手续费
     */
    public final TableField<BusinessCwRecoardRecord, String> YF_SXFXF = createField("yf_sxfxf", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "运费对账——运费手续费");

    /**
     * The column <code>st.business_cw_recoard.yf_sjyfze</code>. 运费对账——司机运费总额
     */
    public final TableField<BusinessCwRecoardRecord, String> YF_SJYFZE = createField("yf_sjyfze", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "运费对账——司机运费总额");

    /**
     * The column <code>st.business_cw_recoard.yf_sjyf1</code>. 运费对账——司机运费1
     */
    public final TableField<BusinessCwRecoardRecord, String> YF_SJYF1 = createField("yf_sjyf1", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "运费对账——司机运费1");

    /**
     * The column <code>st.business_cw_recoard.yf_sjyf2</code>. 运费对账——司机运费2
     */
    public final TableField<BusinessCwRecoardRecord, String> YF_SJYF2 = createField("yf_sjyf2", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "运费对账——司机运费2");

    /**
     * The column <code>st.business_cw_recoard.rb_msg_status</code>. 1:未发送 2:已发送 3：等待确认 4：已完成
     */
    public final TableField<BusinessCwRecoardRecord, Integer> RB_MSG_STATUS = createField("rb_msg_status", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.INTEGER)), this, "1:未发送 2:已发送 3：等待确认 4：已完成");

    /**
     * The column <code>st.business_cw_recoard.dsk_msg_status</code>. 1:未发送 2:已发送 3：等待确认 4：已完成
     */
    public final TableField<BusinessCwRecoardRecord, Integer> DSK_MSG_STATUS = createField("dsk_msg_status", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.INTEGER)), this, "1:未发送 2:已发送 3：等待确认 4：已完成");

    /**
     * The column <code>st.business_cw_recoard.yf_msg_status</code>. 1:未发送 2:已发送 3：等待确认 4：已完成
     */
    public final TableField<BusinessCwRecoardRecord, Integer> YF_MSG_STATUS = createField("yf_msg_status", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.INTEGER)), this, "1:未发送 2:已发送 3：等待确认 4：已完成");

    /**
     * The column <code>st.business_cw_recoard.rb_send_time</code>. 日报表——已发送时间
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_SEND_TIME = createField("rb_send_time", org.jooq.impl.SQLDataType.VARCHAR(255), this, "日报表——已发送时间");

    /**
     * The column <code>st.business_cw_recoard.rb_business_time</code>. 日报表——商家认确时间
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_BUSINESS_TIME = createField("rb_business_time", org.jooq.impl.SQLDataType.VARCHAR(255), this, "日报表——商家认确时间");

    /**
     * The column <code>st.business_cw_recoard.rb_confirm_time</code>. 日报表——务财确认时间
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_CONFIRM_TIME = createField("rb_confirm_time", org.jooq.impl.SQLDataType.VARCHAR(255), this, "日报表——务财确认时间");

    /**
     * The column <code>st.business_cw_recoard.dsk_send_time</code>. 代收款对账——已发送时间
     */
    public final TableField<BusinessCwRecoardRecord, String> DSK_SEND_TIME = createField("dsk_send_time", org.jooq.impl.SQLDataType.VARCHAR(255), this, "代收款对账——已发送时间");

    /**
     * The column <code>st.business_cw_recoard.dsk_business_time</code>. 代收款对账——商家确认时间
     */
    public final TableField<BusinessCwRecoardRecord, String> DSK_BUSINESS_TIME = createField("dsk_business_time", org.jooq.impl.SQLDataType.VARCHAR(255), this, "代收款对账——商家确认时间");

    /**
     * The column <code>st.business_cw_recoard.dsk_confirm_time</code>. 代收款对账——务财确认时间
     */
    public final TableField<BusinessCwRecoardRecord, String> DSK_CONFIRM_TIME = createField("dsk_confirm_time", org.jooq.impl.SQLDataType.VARCHAR(255), this, "代收款对账——务财确认时间");

    /**
     * The column <code>st.business_cw_recoard.yf_send_time</code>. 运费对账——已发送时间
     */
    public final TableField<BusinessCwRecoardRecord, String> YF_SEND_TIME = createField("yf_send_time", org.jooq.impl.SQLDataType.VARCHAR(255), this, "运费对账——已发送时间");

    /**
     * The column <code>st.business_cw_recoard.yf_business_time</code>. 运费对账——商家确认时间
     */
    public final TableField<BusinessCwRecoardRecord, String> YF_BUSINESS_TIME = createField("yf_business_time", org.jooq.impl.SQLDataType.VARCHAR(255), this, "运费对账——商家确认时间");

    /**
     * The column <code>st.business_cw_recoard.yf_confirm_time</code>. 运费对账——财务确认时间
     */
    public final TableField<BusinessCwRecoardRecord, String> YF_CONFIRM_TIME = createField("yf_confirm_time", org.jooq.impl.SQLDataType.VARCHAR(255), this, "运费对账——财务确认时间");

    /**
     * The column <code>st.business_cw_recoard.dfk_msg_status</code>.
     */
    public final TableField<BusinessCwRecoardRecord, Integer> DFK_MSG_STATUS = createField("dfk_msg_status", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>st.business_cw_recoard.dfk_send_time</code>.
     */
    public final TableField<BusinessCwRecoardRecord, String> DFK_SEND_TIME = createField("dfk_send_time", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>st.business_cw_recoard.dfk_business_time</code>.
     */
    public final TableField<BusinessCwRecoardRecord, String> DFK_BUSINESS_TIME = createField("dfk_business_time", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>st.business_cw_recoard.dfk_confirm_time</code>.
     */
    public final TableField<BusinessCwRecoardRecord, String> DFK_CONFIRM_TIME = createField("dfk_confirm_time", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>st.business_cw_recoard.dsk_bz</code>. 代收款备注
     */
    public final TableField<BusinessCwRecoardRecord, String> DSK_BZ = createField("dsk_bz", org.jooq.impl.SQLDataType.VARCHAR(255), this, "代收款备注");

    /**
     * The column <code>st.business_cw_recoard.dfk_bz</code>. 垫付款备注
     */
    public final TableField<BusinessCwRecoardRecord, String> DFK_BZ = createField("dfk_bz", org.jooq.impl.SQLDataType.VARCHAR(255), this, "垫付款备注");

    /**
     * The column <code>st.business_cw_recoard.yf_bz</code>. 运费备注
     */
    public final TableField<BusinessCwRecoardRecord, String> YF_BZ = createField("yf_bz", org.jooq.impl.SQLDataType.VARCHAR(255), this, "运费备注");

    /**
     * The column <code>st.business_cw_recoard.business_yfphone</code>. å•†æˆ·æ‰‹æœºå·â€”â€”è¿è´¹
     */
    public final TableField<BusinessCwRecoardRecord, String> BUSINESS_YFPHONE = createField("business_yfphone", org.jooq.impl.SQLDataType.VARCHAR(50), this, "å•†æˆ·æ‰‹æœºå·â€”â€”è¿è´¹");

    /**
     * The column <code>st.business_cw_recoard.business_yfname</code>. å•†æˆ·å¯¹è´¦äººå§“åâ€”â€”è¿è´¹
     */
    public final TableField<BusinessCwRecoardRecord, String> BUSINESS_YFNAME = createField("business_yfname", org.jooq.impl.SQLDataType.VARCHAR(50), this, "å•†æˆ·å¯¹è´¦äººå§“åâ€”â€”è¿è´¹");

    /**
     * The column <code>st.business_cw_recoard.business_rbphone</code>. å•†æˆ·æ‰‹æœºå·â€”â€”æ—¥æŠ¥
     */
    public final TableField<BusinessCwRecoardRecord, String> BUSINESS_RBPHONE = createField("business_rbphone", org.jooq.impl.SQLDataType.VARCHAR(50), this, "å•†æˆ·æ‰‹æœºå·â€”â€”æ—¥æŠ¥");

    /**
     * The column <code>st.business_cw_recoard.business_rbname</code>. å•†æˆ·å¯¹è´¦äººå§“åâ€”â€”æ—¥æŠ¥
     */
    public final TableField<BusinessCwRecoardRecord, String> BUSINESS_RBNAME = createField("business_rbname", org.jooq.impl.SQLDataType.VARCHAR(50), this, "å•†æˆ·å¯¹è´¦äººå§“åâ€”â€”æ—¥æŠ¥");

    /**
     * The column <code>st.business_cw_recoard.business_dskphone</code>. å•†æˆ·æ‰‹æœºå·â€”â€”ä»£æ”¶æ¬¾
     */
    public final TableField<BusinessCwRecoardRecord, String> BUSINESS_DSKPHONE = createField("business_dskphone", org.jooq.impl.SQLDataType.VARCHAR(50), this, "å•†æˆ·æ‰‹æœºå·â€”â€”ä»£æ”¶æ¬¾");

    /**
     * The column <code>st.business_cw_recoard.business_dskname</code>. å•†æˆ·å¯¹è´¦äººå§“åâ€”â€”ä»£æ”¶æ¬¾
     */
    public final TableField<BusinessCwRecoardRecord, String> BUSINESS_DSKNAME = createField("business_dskname", org.jooq.impl.SQLDataType.VARCHAR(50), this, "å•†æˆ·å¯¹è´¦äººå§“åâ€”â€”ä»£æ”¶æ¬¾");

    /**
     * The column <code>st.business_cw_recoard.business_dfkphone</code>. å•†æˆ·æ‰‹æœºå·â€”â€”åž«ä»˜æ¬¾
     */
    public final TableField<BusinessCwRecoardRecord, String> BUSINESS_DFKPHONE = createField("business_dfkphone", org.jooq.impl.SQLDataType.VARCHAR(50), this, "å•†æˆ·æ‰‹æœºå·â€”â€”åž«ä»˜æ¬¾");

    /**
     * The column <code>st.business_cw_recoard.business_dfkname</code>. å•†æˆ·å¯¹è´¦äººå§“åâ€”â€”åž«ä»˜æ¬¾
     */
    public final TableField<BusinessCwRecoardRecord, String> BUSINESS_DFKNAME = createField("business_dfkname", org.jooq.impl.SQLDataType.VARCHAR(50), this, "å•†æˆ·å¯¹è´¦äººå§“åâ€”â€”åž«ä»˜æ¬¾");

    /**
     * The column <code>st.business_cw_recoard.ticketor_rb</code>. åŠ¡è´¢å¯¹è´¦â€”â€”æ—¥æŠ¥
     */
    public final TableField<BusinessCwRecoardRecord, String> TICKETOR_RB = createField("ticketor_rb", org.jooq.impl.SQLDataType.VARCHAR(50), this, "åŠ¡è´¢å¯¹è´¦â€”â€”æ—¥æŠ¥");

    /**
     * The column <code>st.business_cw_recoard.ticketor_yf</code>. åŠ¡è´¢å¯¹è´¦â€”â€”è¿è´¹
     */
    public final TableField<BusinessCwRecoardRecord, String> TICKETOR_YF = createField("ticketor_yf", org.jooq.impl.SQLDataType.VARCHAR(50), this, "åŠ¡è´¢å¯¹è´¦â€”â€”è¿è´¹");

    /**
     * The column <code>st.business_cw_recoard.ticketor_dsk</code>. åŠ¡è´¢å¯¹è´¦â€”â€”ä»£æ”¶æ¬¾
     */
    public final TableField<BusinessCwRecoardRecord, String> TICKETOR_DSK = createField("ticketor_dsk", org.jooq.impl.SQLDataType.VARCHAR(50), this, "åŠ¡è´¢å¯¹è´¦â€”â€”ä»£æ”¶æ¬¾");

    /**
     * The column <code>st.business_cw_recoard.ticketor_dfk</code>. åŠ¡è´¢å¯¹è´¦â€”â€”åž«ä»˜æ¬¾
     */
    public final TableField<BusinessCwRecoardRecord, String> TICKETOR_DFK = createField("ticketor_dfk", org.jooq.impl.SQLDataType.VARCHAR(50), this, "åŠ¡è´¢å¯¹è´¦â€”â€”åž«ä»˜æ¬¾");

    /**
     * The column <code>st.business_cw_recoard.yf_sjyf1bz</code>. å¸æœºè¿è´¹1å¤‡æ³¨
     */
    public final TableField<BusinessCwRecoardRecord, String> YF_SJYF1BZ = createField("yf_sjyf1bz", org.jooq.impl.SQLDataType.VARCHAR(50), this, "å¸æœºè¿è´¹1å¤‡æ³¨");

    /**
     * The column <code>st.business_cw_recoard.yf_sjyf2bz</code>. å¸æœºè¿è´¹2å¤‡æ³¨
     */
    public final TableField<BusinessCwRecoardRecord, String> YF_SJYF2BZ = createField("yf_sjyf2bz", org.jooq.impl.SQLDataType.VARCHAR(50), this, "å¸æœºè¿è´¹2å¤‡æ³¨");

    /**
     * The column <code>st.business_cw_recoard.yf_sjyf3bz</code>. å¸æœºè¿è´¹3å¤‡æ³¨
     */
    public final TableField<BusinessCwRecoardRecord, String> YF_SJYF3BZ = createField("yf_sjyf3bz", org.jooq.impl.SQLDataType.VARCHAR(50), this, "å¸æœºè¿è´¹3å¤‡æ³¨");

    /**
     * The column <code>st.business_cw_recoard.yf_sjyf4bz</code>. å¸æœºè¿è´¹4å¤‡æ³¨
     */
    public final TableField<BusinessCwRecoardRecord, String> YF_SJYF4BZ = createField("yf_sjyf4bz", org.jooq.impl.SQLDataType.VARCHAR(50), this, "å¸æœºè¿è´¹4å¤‡æ³¨");

    /**
     * The column <code>st.business_cw_recoard.yf_sjyf5bz</code>. å¸æœºè¿è´¹5å¤‡æ³¨
     */
    public final TableField<BusinessCwRecoardRecord, String> YF_SJYF5BZ = createField("yf_sjyf5bz", org.jooq.impl.SQLDataType.VARCHAR(50), this, "å¸æœºè¿è´¹5å¤‡æ³¨");

    /**
     * The column <code>st.business_cw_recoard.rbyffjf</code>. 运费附加费
     */
    public final TableField<BusinessCwRecoardRecord, String> RBYFFJF = createField("rbyffjf", org.jooq.impl.SQLDataType.VARCHAR(50).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "运费附加费");

    /**
     * The column <code>st.business_cw_recoard.created_at</code>. 记录插入时间
     */
    public final TableField<BusinessCwRecoardRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "记录插入时间");

    /**
     * The column <code>st.business_cw_recoard.rb_qm_ps_order_id</code>. 期末票数id组
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_QM_PS_ORDER_ID = createField("rb_qm_ps_order_id", org.jooq.impl.SQLDataType.CLOB, this, "期末票数id组");

    /**
     * The column <code>st.business_cw_recoard.flag</code>. 0:正常 1：修复
     */
    public final TableField<BusinessCwRecoardRecord, Integer> FLAG = createField("flag", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "0:正常 1：修复");

    /**
     * The column <code>st.business_cw_recoard.rb_yc_ps_tmp</code>. 日报表——异常处理——票数
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_YC_PS_TMP = createField("rb_yc_ps_tmp", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "日报表——异常处理——票数");

    /**
     * The column <code>st.business_cw_recoard.rb_yc_je_tmp</code>. 日报表——异常处理——金额
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_YC_JE_TMP = createField("rb_yc_je_tmp", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "日报表——异常处理——金额");

    /**
     * The column <code>st.business_cw_recoard.rb_yc_yf_tmp</code>. 日报表——异常处理——运费
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_YC_YF_TMP = createField("rb_yc_yf_tmp", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "日报表——异常处理——运费");

    /**
     * The column <code>st.business_cw_recoard.rb_yc_dshk_tmp</code>. 日报表——异常处理——代收货款
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_YC_DSHK_TMP = createField("rb_yc_dshk_tmp", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "日报表——异常处理——代收货款");

    /**
     * The column <code>st.business_cw_recoard.rb_yc_dfk_tmp</code>. 日报表——异常处理——垫付款
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_YC_DFK_TMP = createField("rb_yc_dfk_tmp", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "日报表——异常处理——垫付款");

    /**
     * The column <code>st.business_cw_recoard.rb_qc_fwf</code>. 期初——服务费
     */
    public final TableField<BusinessCwRecoardRecord, BigDecimal> RB_QC_FWF = createField("rb_qc_fwf", org.jooq.impl.SQLDataType.DECIMAL(50, 2).defaultValue(org.jooq.impl.DSL.inline("0.00", org.jooq.impl.SQLDataType.DECIMAL)), this, "期初——服务费");

    /**
     * The column <code>st.business_cw_recoard.rb_qm_fwf</code>. 期末——服务费
     */
    public final TableField<BusinessCwRecoardRecord, BigDecimal> RB_QM_FWF = createField("rb_qm_fwf", org.jooq.impl.SQLDataType.DECIMAL(50, 2).defaultValue(org.jooq.impl.DSL.inline("0.00", org.jooq.impl.SQLDataType.DECIMAL)), this, "期末——服务费");

    /**
     * The column <code>st.business_cw_recoard.rb_bq_fwf</code>. 本期——服务费
     */
    public final TableField<BusinessCwRecoardRecord, BigDecimal> RB_BQ_FWF = createField("rb_bq_fwf", org.jooq.impl.SQLDataType.DECIMAL(50, 2).defaultValue(org.jooq.impl.DSL.inline("0.00", org.jooq.impl.SQLDataType.DECIMAL)), this, "本期——服务费");

    /**
     * The column <code>st.business_cw_recoard.rb_xj_fwf</code>. 小计——服务费
     */
    public final TableField<BusinessCwRecoardRecord, BigDecimal> RB_XJ_FWF = createField("rb_xj_fwf", org.jooq.impl.SQLDataType.DECIMAL(50, 2).defaultValue(org.jooq.impl.DSL.inline("0.00", org.jooq.impl.SQLDataType.DECIMAL)), this, "小计——服务费");

    /**
     * The column <code>st.business_cw_recoard.rb_tf_fwf</code>. 提付——服务费
     */
    public final TableField<BusinessCwRecoardRecord, BigDecimal> RB_TF_FWF = createField("rb_tf_fwf", org.jooq.impl.SQLDataType.DECIMAL(50, 2).defaultValue(org.jooq.impl.DSL.inline("0.00", org.jooq.impl.SQLDataType.DECIMAL)), this, "提付——服务费");

    /**
     * The column <code>st.business_cw_recoard.rb_xf_fwf</code>. 现付——服务费
     */
    public final TableField<BusinessCwRecoardRecord, BigDecimal> RB_XF_FWF = createField("rb_xf_fwf", org.jooq.impl.SQLDataType.DECIMAL(50, 2).defaultValue(org.jooq.impl.DSL.inline("0.00", org.jooq.impl.SQLDataType.DECIMAL)), this, "现付——服务费");

    /**
     * The column <code>st.business_cw_recoard.rb_fhd_fwf</code>. 回单付——服务费
     */
    public final TableField<BusinessCwRecoardRecord, BigDecimal> RB_FHD_FWF = createField("rb_fhd_fwf", org.jooq.impl.SQLDataType.DECIMAL(50, 2).defaultValue(org.jooq.impl.DSL.inline("0.00", org.jooq.impl.SQLDataType.DECIMAL)), this, "回单付——服务费");

    /**
     * The column <code>st.business_cw_recoard.rb_yc_fwf</code>. 异常——服务费
     */
    public final TableField<BusinessCwRecoardRecord, BigDecimal> RB_YC_FWF = createField("rb_yc_fwf", org.jooq.impl.SQLDataType.DECIMAL(50, 2).defaultValue(org.jooq.impl.DSL.inline("0.00", org.jooq.impl.SQLDataType.DECIMAL)), this, "异常——服务费");

    /**
     * The column <code>st.business_cw_recoard.ycfwf</code>. 异常修改——服务费
     */
    public final TableField<BusinessCwRecoardRecord, BigDecimal> YCFWF = createField("ycfwf", org.jooq.impl.SQLDataType.DECIMAL(50, 2).defaultValue(org.jooq.impl.DSL.inline("0.00", org.jooq.impl.SQLDataType.DECIMAL)), this, "异常修改——服务费");

    /**
     * The column <code>st.business_cw_recoard.rb_zdyc</code>.
     */
    public final TableField<BusinessCwRecoardRecord, String> RB_ZDYC = createField("rb_zdyc", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>st.business_cw_recoard.advance_payment</code>. 华凌垫付（运费贷）
     */
    public final TableField<BusinessCwRecoardRecord, BigDecimal> ADVANCE_PAYMENT = createField("advance_payment", org.jooq.impl.SQLDataType.DECIMAL(50, 2).defaultValue(org.jooq.impl.DSL.inline("0.00", org.jooq.impl.SQLDataType.DECIMAL)), this, "华凌垫付（运费贷）");

    /**
     * The column <code>st.business_cw_recoard.advance_payment_remark</code>.
     */
    public final TableField<BusinessCwRecoardRecord, String> ADVANCE_PAYMENT_REMARK = createField("advance_payment_remark", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>st.business_cw_recoard.ledger_hm_fee</code>. 台账实际余额
     */
    public final TableField<BusinessCwRecoardRecord, BigDecimal> LEDGER_HM_FEE = createField("ledger_hm_fee", org.jooq.impl.SQLDataType.DECIMAL(50, 2).defaultValue(org.jooq.impl.DSL.inline("0.00", org.jooq.impl.SQLDataType.DECIMAL)), this, "台账实际余额");

    /**
     * The column <code>st.business_cw_recoard.ledger_remark</code>.
     */
    public final TableField<BusinessCwRecoardRecord, String> LEDGER_REMARK = createField("ledger_remark", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>st.business_cw_recoard.ledger_status</code>.
     */
    public final TableField<BusinessCwRecoardRecord, Byte> LEDGER_STATUS = createField("ledger_status", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>st.business_cw_recoard.ledger_abnormal_fee</code>. 台账异常金额
     */
    public final TableField<BusinessCwRecoardRecord, BigDecimal> LEDGER_ABNORMAL_FEE = createField("ledger_abnormal_fee", org.jooq.impl.SQLDataType.DECIMAL(50, 2).defaultValue(org.jooq.impl.DSL.inline("0.00", org.jooq.impl.SQLDataType.DECIMAL)), this, "台账异常金额");

    /**
     * The column <code>st.business_cw_recoard.labor_cost</code>. 人工费
     */
    public final TableField<BusinessCwRecoardRecord, BigDecimal> LABOR_COST = createField("labor_cost", org.jooq.impl.SQLDataType.DECIMAL(50, 2).defaultValue(org.jooq.impl.DSL.inline("0.00", org.jooq.impl.SQLDataType.DECIMAL)), this, "人工费");

    /**
     * The column <code>st.business_cw_recoard.collection_status</code>. 0:返还给托运部 1:返还给客户
     */
    public final TableField<BusinessCwRecoardRecord, Byte> COLLECTION_STATUS = createField("collection_status", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "0:返还给托运部 1:返还给客户");

    /**
     * Create a <code>st.business_cw_recoard</code> table reference
     */
    public BusinessCwRecoard() {
        this(DSL.name("business_cw_recoard"), null);
    }

    /**
     * Create an aliased <code>st.business_cw_recoard</code> table reference
     */
    public BusinessCwRecoard(String alias) {
        this(DSL.name(alias), BUSINESS_CW_RECOARD);
    }

    /**
     * Create an aliased <code>st.business_cw_recoard</code> table reference
     */
    public BusinessCwRecoard(Name alias) {
        this(alias, BUSINESS_CW_RECOARD);
    }

    private BusinessCwRecoard(Name alias, Table<BusinessCwRecoardRecord> aliased) {
        this(alias, aliased, null);
    }

    private BusinessCwRecoard(Name alias, Table<BusinessCwRecoardRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return St.ST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.BUSINESS_CW_RECOARD_IDX_BUSINESS_ID, Indexes.BUSINESS_CW_RECOARD_IDX_LINE_CODE, Indexes.BUSINESS_CW_RECOARD_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<BusinessCwRecoardRecord, Integer> getIdentity() {
        return Keys.IDENTITY_BUSINESS_CW_RECOARD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<BusinessCwRecoardRecord> getPrimaryKey() {
        return Keys.KEY_BUSINESS_CW_RECOARD_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<BusinessCwRecoardRecord>> getKeys() {
        return Arrays.<UniqueKey<BusinessCwRecoardRecord>>asList(Keys.KEY_BUSINESS_CW_RECOARD_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BusinessCwRecoard as(String alias) {
        return new BusinessCwRecoard(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BusinessCwRecoard as(Name alias) {
        return new BusinessCwRecoard(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public BusinessCwRecoard rename(String name) {
        return new BusinessCwRecoard(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BusinessCwRecoard rename(Name name) {
        return new BusinessCwRecoard(name, null);
    }
}
