/*
 * This file is generated by jOOQ.
*/
package com.ebupt.admin.database.tables;


import com.ebupt.admin.database.Indexes;
import com.ebupt.admin.database.Keys;
import com.ebupt.admin.database.St;
import com.ebupt.admin.database.tables.records.CollectionFeeRefundsRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CollectionFeeRefunds extends TableImpl<CollectionFeeRefundsRecord> {

    private static final long serialVersionUID = 2000555054;

    /**
     * The reference instance of <code>st.collection_fee_refunds</code>
     */
    public static final CollectionFeeRefunds COLLECTION_FEE_REFUNDS = new CollectionFeeRefunds();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CollectionFeeRefundsRecord> getRecordType() {
        return CollectionFeeRefundsRecord.class;
    }

    /**
     * The column <code>st.collection_fee_refunds.id</code>.
     */
    public final TableField<CollectionFeeRefundsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>st.collection_fee_refunds.order_id</code>.
     */
    public final TableField<CollectionFeeRefundsRecord, Integer> ORDER_ID = createField("order_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>st.collection_fee_refunds.order_code</code>.
     */
    public final TableField<CollectionFeeRefundsRecord, String> ORDER_CODE = createField("order_code", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>st.collection_fee_refunds.line_code</code>.
     */
    public final TableField<CollectionFeeRefundsRecord, String> LINE_CODE = createField("line_code", org.jooq.impl.SQLDataType.VARCHAR(3), this, "");

    /**
     * The column <code>st.collection_fee_refunds.business_id</code>.
     */
    public final TableField<CollectionFeeRefundsRecord, Integer> BUSINESS_ID = createField("business_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>st.collection_fee_refunds.status</code>. 1:待打款 2:打款中 3:打款成功 4:打款失败
     */
    public final TableField<CollectionFeeRefundsRecord, Byte> STATUS = createField("status", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.TINYINT)), this, "1:待打款 2:打款中 3:打款成功 4:打款失败");

    /**
     * The column <code>st.collection_fee_refunds.receive_money</code>. 应收金额
     */
    public final TableField<CollectionFeeRefundsRecord, Integer> RECEIVE_MONEY = createField("receive_money", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "应收金额");

    /**
     * The column <code>st.collection_fee_refunds.service_charge</code>. 手续费
     */
    public final TableField<CollectionFeeRefundsRecord, Integer> SERVICE_CHARGE = createField("service_charge", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "手续费");

    /**
     * The column <code>st.collection_fee_refunds.return_money</code>. 返还金额
     */
    public final TableField<CollectionFeeRefundsRecord, Integer> RETURN_MONEY = createField("return_money", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "返还金额");

    /**
     * The column <code>st.collection_fee_refunds.remark</code>. 备注
     */
    public final TableField<CollectionFeeRefundsRecord, String> REMARK = createField("remark", org.jooq.impl.SQLDataType.VARCHAR(100), this, "备注");

    /**
     * The column <code>st.collection_fee_refunds.can_payment_at</code>. 可以打款日期
     */
    public final TableField<CollectionFeeRefundsRecord, Timestamp> CAN_PAYMENT_AT = createField("can_payment_at", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "可以打款日期");

    /**
     * The column <code>st.collection_fee_refunds.collection_fee_admin</code>. 代收办理账号
     */
    public final TableField<CollectionFeeRefundsRecord, String> COLLECTION_FEE_ADMIN = createField("collection_fee_admin", org.jooq.impl.SQLDataType.VARCHAR(20), this, "代收办理账号");

    /**
     * The column <code>st.collection_fee_refunds.collection_fee_user</code>. 代收提取员
     */
    public final TableField<CollectionFeeRefundsRecord, String> COLLECTION_FEE_USER = createField("collection_fee_user", org.jooq.impl.SQLDataType.VARCHAR(20), this, "代收提取员");

    /**
     * The column <code>st.collection_fee_refunds.collection_fee_phone</code>. 收提取人代手机号
     */
    public final TableField<CollectionFeeRefundsRecord, String> COLLECTION_FEE_PHONE = createField("collection_fee_phone", org.jooq.impl.SQLDataType.VARCHAR(20), this, "收提取人代手机号");

    /**
     * The column <code>st.collection_fee_refunds.collection_fee_status</code>. 代收提取状态
     */
    public final TableField<CollectionFeeRefundsRecord, Byte> COLLECTION_FEE_STATUS = createField("collection_fee_status", org.jooq.impl.SQLDataType.TINYINT, this, "代收提取状态");

    /**
     * The column <code>st.collection_fee_refunds.collection_fee_bank_name</code>. 代收提取人开户行
     */
    public final TableField<CollectionFeeRefundsRecord, String> COLLECTION_FEE_BANK_NAME = createField("collection_fee_bank_name", org.jooq.impl.SQLDataType.VARCHAR(30), this, "代收提取人开户行");

    /**
     * The column <code>st.collection_fee_refunds.collection_fee_bank_code</code>. 开户行code
     */
    public final TableField<CollectionFeeRefundsRecord, String> COLLECTION_FEE_BANK_CODE = createField("collection_fee_bank_code", org.jooq.impl.SQLDataType.VARCHAR(20), this, "开户行code");

    /**
     * The column <code>st.collection_fee_refunds.collection_fee_bank_num</code>. 代收提取人银行卡号
     */
    public final TableField<CollectionFeeRefundsRecord, String> COLLECTION_FEE_BANK_NUM = createField("collection_fee_bank_num", org.jooq.impl.SQLDataType.VARCHAR(20), this, "代收提取人银行卡号");

    /**
     * The column <code>st.collection_fee_refunds.collection_fee_bank_branch_name</code>. 开户分行名称
     */
    public final TableField<CollectionFeeRefundsRecord, String> COLLECTION_FEE_BANK_BRANCH_NAME = createField("collection_fee_bank_branch_name", org.jooq.impl.SQLDataType.VARCHAR(20), this, "开户分行名称");

    /**
     * The column <code>st.collection_fee_refunds.collection_fee_bank_branch_code</code>. 开户分行代码
     */
    public final TableField<CollectionFeeRefundsRecord, String> COLLECTION_FEE_BANK_BRANCH_CODE = createField("collection_fee_bank_branch_code", org.jooq.impl.SQLDataType.VARCHAR(20), this, "开户分行代码");

    /**
     * The column <code>st.collection_fee_refunds.collection_fee_bank_province</code>. 省份
     */
    public final TableField<CollectionFeeRefundsRecord, String> COLLECTION_FEE_BANK_PROVINCE = createField("collection_fee_bank_province", org.jooq.impl.SQLDataType.VARCHAR(20), this, "省份");

    /**
     * The column <code>st.collection_fee_refunds.collection_fee_card_name</code>. 身份证姓名
     */
    public final TableField<CollectionFeeRefundsRecord, String> COLLECTION_FEE_CARD_NAME = createField("collection_fee_card_name", org.jooq.impl.SQLDataType.VARCHAR(20), this, "身份证姓名");

    /**
     * The column <code>st.collection_fee_refunds.collection_fee_card_num</code>. 身份证号
     */
    public final TableField<CollectionFeeRefundsRecord, String> COLLECTION_FEE_CARD_NUM = createField("collection_fee_card_num", org.jooq.impl.SQLDataType.VARCHAR(20), this, "身份证号");

    /**
     * The column <code>st.collection_fee_refunds.collection_fee_card_photo</code>. 代收提取人代收身份证照片
     */
    public final TableField<CollectionFeeRefundsRecord, String> COLLECTION_FEE_CARD_PHOTO = createField("collection_fee_card_photo", org.jooq.impl.SQLDataType.VARCHAR(100), this, "代收提取人代收身份证照片");

    /**
     * The column <code>st.collection_fee_refunds.collection_fee_photo</code>. 代收提取人提取人照片
     */
    public final TableField<CollectionFeeRefundsRecord, String> COLLECTION_FEE_PHOTO = createField("collection_fee_photo", org.jooq.impl.SQLDataType.VARCHAR(100), this, "代收提取人提取人照片");

    /**
     * The column <code>st.collection_fee_refunds.existed</code>. 银行卡信息是否存在
     */
    public final TableField<CollectionFeeRefundsRecord, Boolean> EXISTED = createField("existed", org.jooq.impl.SQLDataType.BIT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("b'0'", org.jooq.impl.SQLDataType.BIT)), this, "银行卡信息是否存在");

    /**
     * The column <code>st.collection_fee_refunds.created_at</code>.
     */
    public final TableField<CollectionFeeRefundsRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>st.collection_fee_refunds.updated_at</code>.
     */
    public final TableField<CollectionFeeRefundsRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>st.collection_fee_refunds.actual_payment_at</code>. 成功打款时间
     */
    public final TableField<CollectionFeeRefundsRecord, Timestamp> ACTUAL_PAYMENT_AT = createField("actual_payment_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "成功打款时间");

    /**
     * The column <code>st.collection_fee_refunds.payment_at</code>.
     */
    public final TableField<CollectionFeeRefundsRecord, Timestamp> PAYMENT_AT = createField("payment_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>st.collection_fee_refunds.ticket_at</code>. 办票时间
     */
    public final TableField<CollectionFeeRefundsRecord, Timestamp> TICKET_AT = createField("ticket_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "办票时间");

    /**
     * The column <code>st.collection_fee_refunds.bank_create_at</code>. 银行信息添加时间
     */
    public final TableField<CollectionFeeRefundsRecord, Timestamp> BANK_CREATE_AT = createField("bank_create_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "银行信息添加时间");

    /**
     * Create a <code>st.collection_fee_refunds</code> table reference
     */
    public CollectionFeeRefunds() {
        this(DSL.name("collection_fee_refunds"), null);
    }

    /**
     * Create an aliased <code>st.collection_fee_refunds</code> table reference
     */
    public CollectionFeeRefunds(String alias) {
        this(DSL.name(alias), COLLECTION_FEE_REFUNDS);
    }

    /**
     * Create an aliased <code>st.collection_fee_refunds</code> table reference
     */
    public CollectionFeeRefunds(Name alias) {
        this(alias, COLLECTION_FEE_REFUNDS);
    }

    private CollectionFeeRefunds(Name alias, Table<CollectionFeeRefundsRecord> aliased) {
        this(alias, aliased, null);
    }

    private CollectionFeeRefunds(Name alias, Table<CollectionFeeRefundsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return St.ST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.COLLECTION_FEE_REFUNDS_INX_ORDER_ID, Indexes.COLLECTION_FEE_REFUNDS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CollectionFeeRefundsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_COLLECTION_FEE_REFUNDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CollectionFeeRefundsRecord> getPrimaryKey() {
        return Keys.KEY_COLLECTION_FEE_REFUNDS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CollectionFeeRefundsRecord>> getKeys() {
        return Arrays.<UniqueKey<CollectionFeeRefundsRecord>>asList(Keys.KEY_COLLECTION_FEE_REFUNDS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CollectionFeeRefunds as(String alias) {
        return new CollectionFeeRefunds(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CollectionFeeRefunds as(Name alias) {
        return new CollectionFeeRefunds(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CollectionFeeRefunds rename(String name) {
        return new CollectionFeeRefunds(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CollectionFeeRefunds rename(Name name) {
        return new CollectionFeeRefunds(name, null);
    }
}
