/*
 * This file is generated by jOOQ.
*/
package com.ebupt.admin.database.tables;


import com.ebupt.admin.database.Indexes;
import com.ebupt.admin.database.Keys;
import com.ebupt.admin.database.St;
import com.ebupt.admin.database.tables.records.CompanyRoleRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CompanyRole extends TableImpl<CompanyRoleRecord> {

    private static final long serialVersionUID = 761082447;

    /**
     * The reference instance of <code>st.company_role</code>
     */
    public static final CompanyRole COMPANY_ROLE = new CompanyRole();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CompanyRoleRecord> getRecordType() {
        return CompanyRoleRecord.class;
    }

    /**
     * The column <code>st.company_role.id</code>.
     */
    public final TableField<CompanyRoleRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>st.company_role.company_id</code>. 物流公司ID
     */
    public final TableField<CompanyRoleRecord, Integer> COMPANY_ID = createField("company_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "物流公司ID");

    /**
     * The column <code>st.company_role.name</code>. 角色名
     */
    public final TableField<CompanyRoleRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "角色名");

    /**
     * The column <code>st.company_role.enabled</code>. 是否存在标志位
     */
    public final TableField<CompanyRoleRecord, Boolean> ENABLED = createField("enabled", org.jooq.impl.SQLDataType.BIT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("b'1'", org.jooq.impl.SQLDataType.BIT)), this, "是否存在标志位");

    /**
     * The column <code>st.company_role.created_at</code>.
     */
    public final TableField<CompanyRoleRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>st.company_role.updated_at</code>.
     */
    public final TableField<CompanyRoleRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>st.company_role</code> table reference
     */
    public CompanyRole() {
        this(DSL.name("company_role"), null);
    }

    /**
     * Create an aliased <code>st.company_role</code> table reference
     */
    public CompanyRole(String alias) {
        this(DSL.name(alias), COMPANY_ROLE);
    }

    /**
     * Create an aliased <code>st.company_role</code> table reference
     */
    public CompanyRole(Name alias) {
        this(alias, COMPANY_ROLE);
    }

    private CompanyRole(Name alias, Table<CompanyRoleRecord> aliased) {
        this(alias, aliased, null);
    }

    private CompanyRole(Name alias, Table<CompanyRoleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return St.ST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.COMPANY_ROLE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CompanyRoleRecord, Integer> getIdentity() {
        return Keys.IDENTITY_COMPANY_ROLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CompanyRoleRecord> getPrimaryKey() {
        return Keys.KEY_COMPANY_ROLE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CompanyRoleRecord>> getKeys() {
        return Arrays.<UniqueKey<CompanyRoleRecord>>asList(Keys.KEY_COMPANY_ROLE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompanyRole as(String alias) {
        return new CompanyRole(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompanyRole as(Name alias) {
        return new CompanyRole(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CompanyRole rename(String name) {
        return new CompanyRole(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CompanyRole rename(Name name) {
        return new CompanyRole(name, null);
    }
}
