/*
 * This file is generated by jOOQ.
*/
package com.ebupt.admin.database.tables;


import com.ebupt.admin.database.Indexes;
import com.ebupt.admin.database.Keys;
import com.ebupt.admin.database.St;
import com.ebupt.admin.database.tables.records.CwRoleMenuRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CwRoleMenu extends TableImpl<CwRoleMenuRecord> {

    private static final long serialVersionUID = 1825851015;

    /**
     * The reference instance of <code>st.cw_role_menu</code>
     */
    public static final CwRoleMenu CW_ROLE_MENU = new CwRoleMenu();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CwRoleMenuRecord> getRecordType() {
        return CwRoleMenuRecord.class;
    }

    /**
     * The column <code>st.cw_role_menu.id</code>.
     */
    public final TableField<CwRoleMenuRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>st.cw_role_menu.role_id</code>.
     */
    public final TableField<CwRoleMenuRecord, Integer> ROLE_ID = createField("role_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>st.cw_role_menu.menu_id</code>.
     */
    public final TableField<CwRoleMenuRecord, Integer> MENU_ID = createField("menu_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>st.cw_role_menu.create_time</code>.
     */
    public final TableField<CwRoleMenuRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>st.cw_role_menu.is_delete</code>. 0:有效  1：失效
     */
    public final TableField<CwRoleMenuRecord, Integer> IS_DELETE = createField("is_delete", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "0:有效  1：失效");

    /**
     * Create a <code>st.cw_role_menu</code> table reference
     */
    public CwRoleMenu() {
        this(DSL.name("cw_role_menu"), null);
    }

    /**
     * Create an aliased <code>st.cw_role_menu</code> table reference
     */
    public CwRoleMenu(String alias) {
        this(DSL.name(alias), CW_ROLE_MENU);
    }

    /**
     * Create an aliased <code>st.cw_role_menu</code> table reference
     */
    public CwRoleMenu(Name alias) {
        this(alias, CW_ROLE_MENU);
    }

    private CwRoleMenu(Name alias, Table<CwRoleMenuRecord> aliased) {
        this(alias, aliased, null);
    }

    private CwRoleMenu(Name alias, Table<CwRoleMenuRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return St.ST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CW_ROLE_MENU_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CwRoleMenuRecord, Integer> getIdentity() {
        return Keys.IDENTITY_CW_ROLE_MENU;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CwRoleMenuRecord> getPrimaryKey() {
        return Keys.KEY_CW_ROLE_MENU_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CwRoleMenuRecord>> getKeys() {
        return Arrays.<UniqueKey<CwRoleMenuRecord>>asList(Keys.KEY_CW_ROLE_MENU_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CwRoleMenu as(String alias) {
        return new CwRoleMenu(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CwRoleMenu as(Name alias) {
        return new CwRoleMenu(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CwRoleMenu rename(String name) {
        return new CwRoleMenu(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CwRoleMenu rename(Name name) {
        return new CwRoleMenu(name, null);
    }
}
