/*
 * This file is generated by jOOQ.
*/
package com.ebupt.admin.database.tables;


import com.ebupt.admin.database.Indexes;
import com.ebupt.admin.database.Keys;
import com.ebupt.admin.database.St;
import com.ebupt.admin.database.tables.records.PoliceLineRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PoliceLine extends TableImpl<PoliceLineRecord> {

    private static final long serialVersionUID = -298292353;

    /**
     * The reference instance of <code>st.police_line</code>
     */
    public static final PoliceLine POLICE_LINE = new PoliceLine();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PoliceLineRecord> getRecordType() {
        return PoliceLineRecord.class;
    }

    /**
     * The column <code>st.police_line.id</code>.
     */
    public final TableField<PoliceLineRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>st.police_line.police_id</code>.
     */
    public final TableField<PoliceLineRecord, Integer> POLICE_ID = createField("police_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>st.police_line.line_id</code>.
     */
    public final TableField<PoliceLineRecord, Integer> LINE_ID = createField("line_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>st.police_line.enabled</code>.
     */
    public final TableField<PoliceLineRecord, Boolean> ENABLED = createField("enabled", org.jooq.impl.SQLDataType.BIT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("b'1'", org.jooq.impl.SQLDataType.BIT)), this, "");

    /**
     * The column <code>st.police_line.created_at</code>.
     */
    public final TableField<PoliceLineRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>st.police_line.updated_at</code>.
     */
    public final TableField<PoliceLineRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>st.police_line</code> table reference
     */
    public PoliceLine() {
        this(DSL.name("police_line"), null);
    }

    /**
     * Create an aliased <code>st.police_line</code> table reference
     */
    public PoliceLine(String alias) {
        this(DSL.name(alias), POLICE_LINE);
    }

    /**
     * Create an aliased <code>st.police_line</code> table reference
     */
    public PoliceLine(Name alias) {
        this(alias, POLICE_LINE);
    }

    private PoliceLine(Name alias, Table<PoliceLineRecord> aliased) {
        this(alias, aliased, null);
    }

    private PoliceLine(Name alias, Table<PoliceLineRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return St.ST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.POLICE_LINE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<PoliceLineRecord, Integer> getIdentity() {
        return Keys.IDENTITY_POLICE_LINE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PoliceLineRecord> getPrimaryKey() {
        return Keys.KEY_POLICE_LINE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PoliceLineRecord>> getKeys() {
        return Arrays.<UniqueKey<PoliceLineRecord>>asList(Keys.KEY_POLICE_LINE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PoliceLine as(String alias) {
        return new PoliceLine(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PoliceLine as(Name alias) {
        return new PoliceLine(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PoliceLine rename(String name) {
        return new PoliceLine(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PoliceLine rename(Name name) {
        return new PoliceLine(name, null);
    }
}
