/*
 * This file is generated by jOOQ.
*/
package com.ebupt.admin.database.tables;


import com.ebupt.admin.database.Indexes;
import com.ebupt.admin.database.Keys;
import com.ebupt.admin.database.St;
import com.ebupt.admin.database.tables.records.TBackstageRoleMenuRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TBackstageRoleMenu extends TableImpl<TBackstageRoleMenuRecord> {

    private static final long serialVersionUID = 847412504;

    /**
     * The reference instance of <code>st.t_backstage_role_menu</code>
     */
    public static final TBackstageRoleMenu T_BACKSTAGE_ROLE_MENU = new TBackstageRoleMenu();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TBackstageRoleMenuRecord> getRecordType() {
        return TBackstageRoleMenuRecord.class;
    }

    /**
     * The column <code>st.t_backstage_role_menu.id</code>.
     */
    public final TableField<TBackstageRoleMenuRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>st.t_backstage_role_menu.role_id</code>.
     */
    public final TableField<TBackstageRoleMenuRecord, Integer> ROLE_ID = createField("role_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>st.t_backstage_role_menu.menu_id</code>.
     */
    public final TableField<TBackstageRoleMenuRecord, Integer> MENU_ID = createField("menu_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>st.t_backstage_role_menu.create_time</code>.
     */
    public final TableField<TBackstageRoleMenuRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>st.t_backstage_role_menu</code> table reference
     */
    public TBackstageRoleMenu() {
        this(DSL.name("t_backstage_role_menu"), null);
    }

    /**
     * Create an aliased <code>st.t_backstage_role_menu</code> table reference
     */
    public TBackstageRoleMenu(String alias) {
        this(DSL.name(alias), T_BACKSTAGE_ROLE_MENU);
    }

    /**
     * Create an aliased <code>st.t_backstage_role_menu</code> table reference
     */
    public TBackstageRoleMenu(Name alias) {
        this(alias, T_BACKSTAGE_ROLE_MENU);
    }

    private TBackstageRoleMenu(Name alias, Table<TBackstageRoleMenuRecord> aliased) {
        this(alias, aliased, null);
    }

    private TBackstageRoleMenu(Name alias, Table<TBackstageRoleMenuRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return St.ST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_BACKSTAGE_ROLE_MENU_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TBackstageRoleMenuRecord, Integer> getIdentity() {
        return Keys.IDENTITY_T_BACKSTAGE_ROLE_MENU;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TBackstageRoleMenuRecord> getPrimaryKey() {
        return Keys.KEY_T_BACKSTAGE_ROLE_MENU_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TBackstageRoleMenuRecord>> getKeys() {
        return Arrays.<UniqueKey<TBackstageRoleMenuRecord>>asList(Keys.KEY_T_BACKSTAGE_ROLE_MENU_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBackstageRoleMenu as(String alias) {
        return new TBackstageRoleMenu(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBackstageRoleMenu as(Name alias) {
        return new TBackstageRoleMenu(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TBackstageRoleMenu rename(String name) {
        return new TBackstageRoleMenu(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TBackstageRoleMenu rename(Name name) {
        return new TBackstageRoleMenu(name, null);
    }
}
