/*
 * This file is generated by jOOQ.
*/
package com.ebupt.admin.database.tables;


import com.ebupt.admin.database.Indexes;
import com.ebupt.admin.database.Keys;
import com.ebupt.admin.database.St;
import com.ebupt.admin.database.tables.records.TrainRecordRecord;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 班列对账表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TrainRecord extends TableImpl<TrainRecordRecord> {

    private static final long serialVersionUID = -796829768;

    /**
     * The reference instance of <code>st.train_record</code>
     */
    public static final TrainRecord TRAIN_RECORD = new TrainRecord();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TrainRecordRecord> getRecordType() {
        return TrainRecordRecord.class;
    }

    /**
     * The column <code>st.train_record.id</code>.
     */
    public final TableField<TrainRecordRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>st.train_record.business_id</code>.
     */
    public final TableField<TrainRecordRecord, Integer> BUSINESS_ID = createField("business_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>st.train_record.business_name</code>. 托运部名称
     */
    public final TableField<TrainRecordRecord, String> BUSINESS_NAME = createField("business_name", org.jooq.impl.SQLDataType.VARCHAR(30).nullable(false), this, "托运部名称");

    /**
     * The column <code>st.train_record.start_at</code>. 账单开始时间
     */
    public final TableField<TrainRecordRecord, Timestamp> START_AT = createField("start_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "账单开始时间");

    /**
     * The column <code>st.train_record.end_at</code>. 账单结束时间
     */
    public final TableField<TrainRecordRecord, Timestamp> END_AT = createField("end_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0000-00-00 00:00:00", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "账单结束时间");

    /**
     * The column <code>st.train_record.receive_money</code>. 累计收款
     */
    public final TableField<TrainRecordRecord, BigDecimal> RECEIVE_MONEY = createField("receive_money", org.jooq.impl.SQLDataType.DECIMAL(20, 2).nullable(false), this, "累计收款");

    /**
     * The column <code>st.train_record.settle_money</code>. 累计结算
     */
    public final TableField<TrainRecordRecord, BigDecimal> SETTLE_MONEY = createField("settle_money", org.jooq.impl.SQLDataType.DECIMAL(20, 2).nullable(false), this, "累计结算");

    /**
     * The column <code>st.train_record.balance</code>. 余额
     */
    public final TableField<TrainRecordRecord, BigDecimal> BALANCE = createField("balance", org.jooq.impl.SQLDataType.DECIMAL(20, 2).nullable(false), this, "余额");

    /**
     * The column <code>st.train_record.status</code>. 1:未发送 2:已发送 3：等待确认 4：已完成
     */
    public final TableField<TrainRecordRecord, Byte> STATUS = createField("status", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.TINYINT)), this, "1:未发送 2:已发送 3：等待确认 4：已完成");

    /**
     * The column <code>st.train_record.business_confirm_name</code>. 商户确认姓名
     */
    public final TableField<TrainRecordRecord, String> BUSINESS_CONFIRM_NAME = createField("business_confirm_name", org.jooq.impl.SQLDataType.VARCHAR(20), this, "商户确认姓名");

    /**
     * The column <code>st.train_record.business_confirm_phone</code>. 商户对账手机号
     */
    public final TableField<TrainRecordRecord, String> BUSINESS_CONFIRM_PHONE = createField("business_confirm_phone", org.jooq.impl.SQLDataType.VARCHAR(20), this, "商户对账手机号");

    /**
     * The column <code>st.train_record.finance_confirm_name</code>. 财务确认姓名
     */
    public final TableField<TrainRecordRecord, String> FINANCE_CONFIRM_NAME = createField("finance_confirm_name", org.jooq.impl.SQLDataType.VARCHAR(20), this, "财务确认姓名");

    /**
     * The column <code>st.train_record.finance_confirm_phone</code>. 财务对账手机号
     */
    public final TableField<TrainRecordRecord, String> FINANCE_CONFIRM_PHONE = createField("finance_confirm_phone", org.jooq.impl.SQLDataType.VARCHAR(20), this, "财务对账手机号");

    /**
     * The column <code>st.train_record.reason</code>. 拒绝对账原因
     */
    public final TableField<TrainRecordRecord, String> REASON = createField("reason", org.jooq.impl.SQLDataType.VARCHAR(100), this, "拒绝对账原因");

    /**
     * The column <code>st.train_record.send_at</code>. 报表发送时间
     */
    public final TableField<TrainRecordRecord, Timestamp> SEND_AT = createField("send_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "报表发送时间");

    /**
     * The column <code>st.train_record.business_at</code>. 商户确认时间
     */
    public final TableField<TrainRecordRecord, Timestamp> BUSINESS_AT = createField("business_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "商户确认时间");

    /**
     * The column <code>st.train_record.created_at</code>.
     */
    public final TableField<TrainRecordRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>st.train_record.updated_at</code>.
     */
    public final TableField<TrainRecordRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>st.train_record.finance_refused_phone</code>. 财务撤回账号
     */
    public final TableField<TrainRecordRecord, String> FINANCE_REFUSED_PHONE = createField("finance_refused_phone", org.jooq.impl.SQLDataType.VARCHAR(20), this, "财务撤回账号");

    /**
     * The column <code>st.train_record.refused_at</code>. 财务撤回时间
     */
    public final TableField<TrainRecordRecord, Timestamp> REFUSED_AT = createField("refused_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "财务撤回时间");

    /**
     * Create a <code>st.train_record</code> table reference
     */
    public TrainRecord() {
        this(DSL.name("train_record"), null);
    }

    /**
     * Create an aliased <code>st.train_record</code> table reference
     */
    public TrainRecord(String alias) {
        this(DSL.name(alias), TRAIN_RECORD);
    }

    /**
     * Create an aliased <code>st.train_record</code> table reference
     */
    public TrainRecord(Name alias) {
        this(alias, TRAIN_RECORD);
    }

    private TrainRecord(Name alias, Table<TrainRecordRecord> aliased) {
        this(alias, aliased, null);
    }

    private TrainRecord(Name alias, Table<TrainRecordRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "班列对账表");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return St.ST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TRAIN_RECORD_IDX_BUSINESS_ID, Indexes.TRAIN_RECORD_PRIMARY, Indexes.TRAIN_RECORD_UK_BUSINESS_TIME);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TrainRecordRecord, Integer> getIdentity() {
        return Keys.IDENTITY_TRAIN_RECORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TrainRecordRecord> getPrimaryKey() {
        return Keys.KEY_TRAIN_RECORD_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TrainRecordRecord>> getKeys() {
        return Arrays.<UniqueKey<TrainRecordRecord>>asList(Keys.KEY_TRAIN_RECORD_PRIMARY, Keys.KEY_TRAIN_RECORD_UK_BUSINESS_TIME);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrainRecord as(String alias) {
        return new TrainRecord(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrainRecord as(Name alias) {
        return new TrainRecord(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TrainRecord rename(String name) {
        return new TrainRecord(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TrainRecord rename(Name name) {
        return new TrainRecord(name, null);
    }
}
