/*
 * This file is generated by jOOQ.
*/
package com.ebupt.admin.database.tables.records;


import com.ebupt.admin.database.tables.ApplyTrain;

import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 申请请车
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ApplyTrainRecord extends UpdatableRecordImpl<ApplyTrainRecord> implements Record14<Integer, Integer, Date, Timestamp, Integer, Integer, Byte, Boolean, Timestamp, Timestamp, Byte, Time, Integer, Integer> {

    private static final long serialVersionUID = -1418485058;

    /**
     * Setter for <code>st.apply_train.id</code>.
     */
    public ApplyTrainRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>st.apply_train.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>st.apply_train.merchant_id</code>. 商户id
     */
    public ApplyTrainRecord setMerchantId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>st.apply_train.merchant_id</code>. 商户id
     */
    public Integer getMerchantId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>st.apply_train.send_date</code>. 发车日期
     */
    public ApplyTrainRecord setSendDate(Date value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>st.apply_train.send_date</code>. 发车日期
     */
    public Date getSendDate() {
        return (Date) get(2);
    }

    /**
     * Setter for <code>st.apply_train.send_time</code>. 发车时间
     */
    public ApplyTrainRecord setSendTime(Timestamp value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>st.apply_train.send_time</code>. 发车时间
     */
    public Timestamp getSendTime() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>st.apply_train.line_id</code>. 线路id
     */
    public ApplyTrainRecord setLineId(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>st.apply_train.line_id</code>. 线路id
     */
    public Integer getLineId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>st.apply_train.carriage_number</code>. 车辆数
     */
    public ApplyTrainRecord setCarriageNumber(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>st.apply_train.carriage_number</code>. 车辆数
     */
    public Integer getCarriageNumber() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>st.apply_train.status</code>. 0-待发车 ，1-运营后端提交请车单，2-已发车
     */
    public ApplyTrainRecord setStatus(Byte value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>st.apply_train.status</code>. 0-待发车 ，1-运营后端提交请车单，2-已发车
     */
    public Byte getStatus() {
        return (Byte) get(6);
    }

    /**
     * Setter for <code>st.apply_train.enabled</code>. 是否可用
     */
    public ApplyTrainRecord setEnabled(Boolean value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>st.apply_train.enabled</code>. 是否可用
     */
    public Boolean getEnabled() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>st.apply_train.created_at</code>.
     */
    public ApplyTrainRecord setCreatedAt(Timestamp value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>st.apply_train.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>st.apply_train.updated_at</code>.
     */
    public ApplyTrainRecord setUpdatedAt(Timestamp value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>st.apply_train.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>st.apply_train.source</code>. 0-托运部，1-运营后端
     */
    public ApplyTrainRecord setSource(Byte value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>st.apply_train.source</code>. 0-托运部，1-运营后端
     */
    public Byte getSource() {
        return (Byte) get(10);
    }

    /**
     * Setter for <code>st.apply_train.line_send_time</code>. 线路发车时间
     */
    public ApplyTrainRecord setLineSendTime(Time value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>st.apply_train.line_send_time</code>. 线路发车时间
     */
    public Time getLineSendTime() {
        return (Time) get(11);
    }

    /**
     * Setter for <code>st.apply_train.work_hour</code>. 运行小时
     */
    public ApplyTrainRecord setWorkHour(Integer value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>st.apply_train.work_hour</code>. 运行小时
     */
    public Integer getWorkHour() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>st.apply_train.work_minute</code>. 运行分钟
     */
    public ApplyTrainRecord setWorkMinute(Integer value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>st.apply_train.work_minute</code>. 运行分钟
     */
    public Integer getWorkMinute() {
        return (Integer) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Integer, Integer, Date, Timestamp, Integer, Integer, Byte, Boolean, Timestamp, Timestamp, Byte, Time, Integer, Integer> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Integer, Integer, Date, Timestamp, Integer, Integer, Byte, Boolean, Timestamp, Timestamp, Byte, Time, Integer, Integer> valuesRow() {
        return (Row14) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ApplyTrain.APPLY_TRAIN.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return ApplyTrain.APPLY_TRAIN.MERCHANT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field3() {
        return ApplyTrain.APPLY_TRAIN.SEND_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return ApplyTrain.APPLY_TRAIN.SEND_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return ApplyTrain.APPLY_TRAIN.LINE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return ApplyTrain.APPLY_TRAIN.CARRIAGE_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field7() {
        return ApplyTrain.APPLY_TRAIN.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field8() {
        return ApplyTrain.APPLY_TRAIN.ENABLED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return ApplyTrain.APPLY_TRAIN.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return ApplyTrain.APPLY_TRAIN.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field11() {
        return ApplyTrain.APPLY_TRAIN.SOURCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Time> field12() {
        return ApplyTrain.APPLY_TRAIN.LINE_SEND_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return ApplyTrain.APPLY_TRAIN.WORK_HOUR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field14() {
        return ApplyTrain.APPLY_TRAIN.WORK_MINUTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getMerchantId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component3() {
        return getSendDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getSendTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getLineId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getCarriageNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component8() {
        return getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component11() {
        return getSource();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Time component12() {
        return getLineSendTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component13() {
        return getWorkHour();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component14() {
        return getWorkMinute();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getMerchantId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value3() {
        return getSendDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getSendTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getLineId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getCarriageNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value8() {
        return getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value11() {
        return getSource();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Time value12() {
        return getLineSendTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getWorkHour();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value14() {
        return getWorkMinute();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplyTrainRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplyTrainRecord value2(Integer value) {
        setMerchantId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplyTrainRecord value3(Date value) {
        setSendDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplyTrainRecord value4(Timestamp value) {
        setSendTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplyTrainRecord value5(Integer value) {
        setLineId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplyTrainRecord value6(Integer value) {
        setCarriageNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplyTrainRecord value7(Byte value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplyTrainRecord value8(Boolean value) {
        setEnabled(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplyTrainRecord value9(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplyTrainRecord value10(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplyTrainRecord value11(Byte value) {
        setSource(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplyTrainRecord value12(Time value) {
        setLineSendTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplyTrainRecord value13(Integer value) {
        setWorkHour(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplyTrainRecord value14(Integer value) {
        setWorkMinute(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplyTrainRecord values(Integer value1, Integer value2, Date value3, Timestamp value4, Integer value5, Integer value6, Byte value7, Boolean value8, Timestamp value9, Timestamp value10, Byte value11, Time value12, Integer value13, Integer value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ApplyTrainRecord
     */
    public ApplyTrainRecord() {
        super(ApplyTrain.APPLY_TRAIN);
    }

    /**
     * Create a detached, initialised ApplyTrainRecord
     */
    public ApplyTrainRecord(Integer id, Integer merchantId, Date sendDate, Timestamp sendTime, Integer lineId, Integer carriageNumber, Byte status, Boolean enabled, Timestamp createdAt, Timestamp updatedAt, Byte source, Time lineSendTime, Integer workHour, Integer workMinute) {
        super(ApplyTrain.APPLY_TRAIN);

        set(0, id);
        set(1, merchantId);
        set(2, sendDate);
        set(3, sendTime);
        set(4, lineId);
        set(5, carriageNumber);
        set(6, status);
        set(7, enabled);
        set(8, createdAt);
        set(9, updatedAt);
        set(10, source);
        set(11, lineSendTime);
        set(12, workHour);
        set(13, workMinute);
    }
}
