/*
 * This file is generated by jOOQ.
*/
package com.ebupt.admin.database.tables.records;


import com.ebupt.admin.database.tables.BusinessUserRole;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BusinessUserRoleRecord extends TableRecordImpl<BusinessUserRoleRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = -147757504;

    /**
     * Setter for <code>st.business_user_role.user_id</code>. 用户ID
     */
    public BusinessUserRoleRecord setUserId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>st.business_user_role.user_id</code>. 用户ID
     */
    public Integer getUserId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>st.business_user_role.role_id</code>. 角色ID
     */
    public BusinessUserRoleRecord setRoleId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>st.business_user_role.role_id</code>. 角色ID
     */
    public Integer getRoleId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return BusinessUserRole.BUSINESS_USER_ROLE.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return BusinessUserRole.BUSINESS_USER_ROLE.ROLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BusinessUserRoleRecord value1(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BusinessUserRoleRecord value2(Integer value) {
        setRoleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BusinessUserRoleRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BusinessUserRoleRecord
     */
    public BusinessUserRoleRecord() {
        super(BusinessUserRole.BUSINESS_USER_ROLE);
    }

    /**
     * Create a detached, initialised BusinessUserRoleRecord
     */
    public BusinessUserRoleRecord(Integer userId, Integer roleId) {
        super(BusinessUserRole.BUSINESS_USER_ROLE);

        set(0, userId);
        set(1, roleId);
    }
}
