/*
 * This file is generated by jOOQ.
*/
package com.ebupt.admin.database.tables.records;


import com.ebupt.admin.database.tables.DebtLimit;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 运费贷线路欠款限额
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DebtLimitRecord extends UpdatableRecordImpl<DebtLimitRecord> implements Record4<Integer, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1489651713;

    /**
     * Setter for <code>st.debt_limit.id</code>. 线路id
     */
    public DebtLimitRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>st.debt_limit.id</code>. 线路id
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>st.debt_limit.limit</code>. 限额
     */
    public DebtLimitRecord setLimit(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>st.debt_limit.limit</code>. 限额
     */
    public Integer getLimit() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>st.debt_limit.created_at</code>.
     */
    public DebtLimitRecord setCreatedAt(Timestamp value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>st.debt_limit.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>st.debt_limit.updated_at</code>.
     */
    public DebtLimitRecord setUpdatedAt(Timestamp value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>st.debt_limit.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return DebtLimit.DEBT_LIMIT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return DebtLimit.DEBT_LIMIT.LIMIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return DebtLimit.DEBT_LIMIT.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return DebtLimit.DEBT_LIMIT.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getLimit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getLimit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DebtLimitRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DebtLimitRecord value2(Integer value) {
        setLimit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DebtLimitRecord value3(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DebtLimitRecord value4(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DebtLimitRecord values(Integer value1, Integer value2, Timestamp value3, Timestamp value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DebtLimitRecord
     */
    public DebtLimitRecord() {
        super(DebtLimit.DEBT_LIMIT);
    }

    /**
     * Create a detached, initialised DebtLimitRecord
     */
    public DebtLimitRecord(Integer id, Integer limit, Timestamp createdAt, Timestamp updatedAt) {
        super(DebtLimit.DEBT_LIMIT);

        set(0, id);
        set(1, limit);
        set(2, createdAt);
        set(3, updatedAt);
    }
}
