/*
 * This file is generated by jOOQ.
*/
package com.ebupt.admin.database.tables.records;


import com.ebupt.admin.database.tables.LedgerInit;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LedgerInitRecord extends UpdatableRecordImpl<LedgerInitRecord> implements Record7<Integer, BigDecimal, Integer, Integer, Timestamp, Timestamp, Boolean> {

    private static final long serialVersionUID = -685401720;

    /**
     * Setter for <code>st.ledger_init.id</code>.
     */
    public LedgerInitRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>st.ledger_init.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>st.ledger_init.ledger_init_fee</code>. 台账实际余额初始值
     */
    public LedgerInitRecord setLedgerInitFee(BigDecimal value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>st.ledger_init.ledger_init_fee</code>. 台账实际余额初始值
     */
    public BigDecimal getLedgerInitFee() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>st.ledger_init.line_id</code>.
     */
    public LedgerInitRecord setLineId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>st.ledger_init.line_id</code>.
     */
    public Integer getLineId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>st.ledger_init.business_id</code>.
     */
    public LedgerInitRecord setBusinessId(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>st.ledger_init.business_id</code>.
     */
    public Integer getBusinessId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>st.ledger_init.created_at</code>.
     */
    public LedgerInitRecord setCreatedAt(Timestamp value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>st.ledger_init.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>st.ledger_init.updated_at</code>.
     */
    public LedgerInitRecord setUpdatedAt(Timestamp value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>st.ledger_init.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>st.ledger_init.enabled</code>.
     */
    public LedgerInitRecord setEnabled(Boolean value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>st.ledger_init.enabled</code>.
     */
    public Boolean getEnabled() {
        return (Boolean) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, BigDecimal, Integer, Integer, Timestamp, Timestamp, Boolean> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, BigDecimal, Integer, Integer, Timestamp, Timestamp, Boolean> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return LedgerInit.LEDGER_INIT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field2() {
        return LedgerInit.LEDGER_INIT.LEDGER_INIT_FEE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return LedgerInit.LEDGER_INIT.LINE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return LedgerInit.LEDGER_INIT.BUSINESS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return LedgerInit.LEDGER_INIT.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return LedgerInit.LEDGER_INIT.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field7() {
        return LedgerInit.LEDGER_INIT.ENABLED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component2() {
        return getLedgerInitFee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getLineId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getBusinessId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component7() {
        return getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value2() {
        return getLedgerInitFee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getLineId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getBusinessId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value7() {
        return getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LedgerInitRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LedgerInitRecord value2(BigDecimal value) {
        setLedgerInitFee(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LedgerInitRecord value3(Integer value) {
        setLineId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LedgerInitRecord value4(Integer value) {
        setBusinessId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LedgerInitRecord value5(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LedgerInitRecord value6(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LedgerInitRecord value7(Boolean value) {
        setEnabled(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LedgerInitRecord values(Integer value1, BigDecimal value2, Integer value3, Integer value4, Timestamp value5, Timestamp value6, Boolean value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LedgerInitRecord
     */
    public LedgerInitRecord() {
        super(LedgerInit.LEDGER_INIT);
    }

    /**
     * Create a detached, initialised LedgerInitRecord
     */
    public LedgerInitRecord(Integer id, BigDecimal ledgerInitFee, Integer lineId, Integer businessId, Timestamp createdAt, Timestamp updatedAt, Boolean enabled) {
        super(LedgerInit.LEDGER_INIT);

        set(0, id);
        set(1, ledgerInitFee);
        set(2, lineId);
        set(3, businessId);
        set(4, createdAt);
        set(5, updatedAt);
        set(6, enabled);
    }
}
