/*
 * This file is generated by jOOQ.
*/
package com.ebupt.admin.database.tables.records;


import com.ebupt.admin.database.tables.MerchantAccountChange;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 商户运费贷账户变更记录
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MerchantAccountChangeRecord extends UpdatableRecordImpl<MerchantAccountChangeRecord> implements Record13<Integer, String, Integer, Byte, Integer, Integer, String, String, String, String, Timestamp, Timestamp, Boolean> {

    private static final long serialVersionUID = -870463795;

    /**
     * Setter for <code>st.merchant_account_change.id</code>.
     */
    public MerchantAccountChangeRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>st.merchant_account_change.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>st.merchant_account_change.no</code>.
     */
    public MerchantAccountChangeRecord setNo(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>st.merchant_account_change.no</code>.
     */
    public String getNo() {
        return (String) get(1);
    }

    /**
     * Setter for <code>st.merchant_account_change.account_id</code>.
     */
    public MerchantAccountChangeRecord setAccountId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>st.merchant_account_change.account_id</code>.
     */
    public Integer getAccountId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>st.merchant_account_change.type</code>.
     */
    public MerchantAccountChangeRecord setType(Byte value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>st.merchant_account_change.type</code>.
     */
    public Byte getType() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>st.merchant_account_change.delta</code>. 账户变化值
     */
    public MerchantAccountChangeRecord setDelta(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>st.merchant_account_change.delta</code>. 账户变化值
     */
    public Integer getDelta() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>st.merchant_account_change.after</code>. 此次变更后账户金额
     */
    public MerchantAccountChangeRecord setAfter(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>st.merchant_account_change.after</code>. 此次变更后账户金额
     */
    public Integer getAfter() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>st.merchant_account_change.detail</code>. 账户各项变更明细
     */
    public MerchantAccountChangeRecord setDetail(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>st.merchant_account_change.detail</code>. 账户各项变更明细
     */
    public String getDetail() {
        return (String) get(6);
    }

    /**
     * Setter for <code>st.merchant_account_change.description</code>.
     */
    public MerchantAccountChangeRecord setDescription(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>st.merchant_account_change.description</code>.
     */
    public String getDescription() {
        return (String) get(7);
    }

    /**
     * Setter for <code>st.merchant_account_change.remark</code>. 财务后台添加备注
     */
    public MerchantAccountChangeRecord setRemark(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>st.merchant_account_change.remark</code>. 财务后台添加备注
     */
    public String getRemark() {
        return (String) get(8);
    }

    /**
     * Setter for <code>st.merchant_account_change.merchant_remark</code>. 商户添加备注
     */
    public MerchantAccountChangeRecord setMerchantRemark(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>st.merchant_account_change.merchant_remark</code>. 商户添加备注
     */
    public String getMerchantRemark() {
        return (String) get(9);
    }

    /**
     * Setter for <code>st.merchant_account_change.created_at</code>.
     */
    public MerchantAccountChangeRecord setCreatedAt(Timestamp value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>st.merchant_account_change.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>st.merchant_account_change.updated_at</code>.
     */
    public MerchantAccountChangeRecord setUpdatedAt(Timestamp value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>st.merchant_account_change.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(11);
    }

    /**
     * Setter for <code>st.merchant_account_change.revoked</code>.
     */
    public MerchantAccountChangeRecord setRevoked(Boolean value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>st.merchant_account_change.revoked</code>.
     */
    public Boolean getRevoked() {
        return (Boolean) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, String, Integer, Byte, Integer, Integer, String, String, String, String, Timestamp, Timestamp, Boolean> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, String, Integer, Byte, Integer, Integer, String, String, String, String, Timestamp, Timestamp, Boolean> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return MerchantAccountChange.MERCHANT_ACCOUNT_CHANGE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return MerchantAccountChange.MERCHANT_ACCOUNT_CHANGE.NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return MerchantAccountChange.MERCHANT_ACCOUNT_CHANGE.ACCOUNT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field4() {
        return MerchantAccountChange.MERCHANT_ACCOUNT_CHANGE.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return MerchantAccountChange.MERCHANT_ACCOUNT_CHANGE.DELTA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return MerchantAccountChange.MERCHANT_ACCOUNT_CHANGE.AFTER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return MerchantAccountChange.MERCHANT_ACCOUNT_CHANGE.DETAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return MerchantAccountChange.MERCHANT_ACCOUNT_CHANGE.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return MerchantAccountChange.MERCHANT_ACCOUNT_CHANGE.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return MerchantAccountChange.MERCHANT_ACCOUNT_CHANGE.MERCHANT_REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return MerchantAccountChange.MERCHANT_ACCOUNT_CHANGE.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field12() {
        return MerchantAccountChange.MERCHANT_ACCOUNT_CHANGE.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field13() {
        return MerchantAccountChange.MERCHANT_ACCOUNT_CHANGE.REVOKED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component4() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getDelta();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getAfter();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getDetail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getMerchantRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component11() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component12() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component13() {
        return getRevoked();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value4() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getDelta();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getAfter();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getDetail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getMerchantRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value12() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value13() {
        return getRevoked();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MerchantAccountChangeRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MerchantAccountChangeRecord value2(String value) {
        setNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MerchantAccountChangeRecord value3(Integer value) {
        setAccountId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MerchantAccountChangeRecord value4(Byte value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MerchantAccountChangeRecord value5(Integer value) {
        setDelta(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MerchantAccountChangeRecord value6(Integer value) {
        setAfter(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MerchantAccountChangeRecord value7(String value) {
        setDetail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MerchantAccountChangeRecord value8(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MerchantAccountChangeRecord value9(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MerchantAccountChangeRecord value10(String value) {
        setMerchantRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MerchantAccountChangeRecord value11(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MerchantAccountChangeRecord value12(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MerchantAccountChangeRecord value13(Boolean value) {
        setRevoked(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MerchantAccountChangeRecord values(Integer value1, String value2, Integer value3, Byte value4, Integer value5, Integer value6, String value7, String value8, String value9, String value10, Timestamp value11, Timestamp value12, Boolean value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MerchantAccountChangeRecord
     */
    public MerchantAccountChangeRecord() {
        super(MerchantAccountChange.MERCHANT_ACCOUNT_CHANGE);
    }

    /**
     * Create a detached, initialised MerchantAccountChangeRecord
     */
    public MerchantAccountChangeRecord(Integer id, String no, Integer accountId, Byte type, Integer delta, Integer after, String detail, String description, String remark, String merchantRemark, Timestamp createdAt, Timestamp updatedAt, Boolean revoked) {
        super(MerchantAccountChange.MERCHANT_ACCOUNT_CHANGE);

        set(0, id);
        set(1, no);
        set(2, accountId);
        set(3, type);
        set(4, delta);
        set(5, after);
        set(6, detail);
        set(7, description);
        set(8, remark);
        set(9, merchantRemark);
        set(10, createdAt);
        set(11, updatedAt);
        set(12, revoked);
    }
}
