/*
 * This file is generated by jOOQ.
*/
package com.ebupt.admin.database.tables.records;


import com.ebupt.admin.database.tables.NoticeInfo;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NoticeInfoRecord extends UpdatableRecordImpl<NoticeInfoRecord> implements Record7<Integer, String, String, String, Integer, Timestamp, Integer> {

    private static final long serialVersionUID = 1839180293;

    /**
     * Setter for <code>st.notice_info.id</code>.
     */
    public NoticeInfoRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>st.notice_info.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>st.notice_info.title</code>. 标题
     */
    public NoticeInfoRecord setTitle(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>st.notice_info.title</code>. 标题
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>st.notice_info.simple_info</code>. 简介
     */
    public NoticeInfoRecord setSimpleInfo(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>st.notice_info.simple_info</code>. 简介
     */
    public String getSimpleInfo() {
        return (String) get(2);
    }

    /**
     * Setter for <code>st.notice_info.info</code>. 内容
     */
    public NoticeInfoRecord setInfo(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>st.notice_info.info</code>. 内容
     */
    public String getInfo() {
        return (String) get(3);
    }

    /**
     * Setter for <code>st.notice_info.is_online</code>. 1，上线，0下线
     */
    public NoticeInfoRecord setIsOnline(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>st.notice_info.is_online</code>. 1，上线，0下线
     */
    public Integer getIsOnline() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>st.notice_info.create_time</code>.
     */
    public NoticeInfoRecord setCreateTime(Timestamp value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>st.notice_info.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>st.notice_info.is_delete</code>. 是否删除
     */
    public NoticeInfoRecord setIsDelete(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>st.notice_info.is_delete</code>. 是否删除
     */
    public Integer getIsDelete() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, String, Integer, Timestamp, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, String, Integer, Timestamp, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return NoticeInfo.NOTICE_INFO.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return NoticeInfo.NOTICE_INFO.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return NoticeInfo.NOTICE_INFO.SIMPLE_INFO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return NoticeInfo.NOTICE_INFO.INFO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return NoticeInfo.NOTICE_INFO.IS_ONLINE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return NoticeInfo.NOTICE_INFO.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return NoticeInfo.NOTICE_INFO.IS_DELETE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getSimpleInfo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getInfo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getIsOnline();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getIsDelete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getSimpleInfo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getInfo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getIsOnline();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getIsDelete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NoticeInfoRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NoticeInfoRecord value2(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NoticeInfoRecord value3(String value) {
        setSimpleInfo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NoticeInfoRecord value4(String value) {
        setInfo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NoticeInfoRecord value5(Integer value) {
        setIsOnline(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NoticeInfoRecord value6(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NoticeInfoRecord value7(Integer value) {
        setIsDelete(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NoticeInfoRecord values(Integer value1, String value2, String value3, String value4, Integer value5, Timestamp value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NoticeInfoRecord
     */
    public NoticeInfoRecord() {
        super(NoticeInfo.NOTICE_INFO);
    }

    /**
     * Create a detached, initialised NoticeInfoRecord
     */
    public NoticeInfoRecord(Integer id, String title, String simpleInfo, String info, Integer isOnline, Timestamp createTime, Integer isDelete) {
        super(NoticeInfo.NOTICE_INFO);

        set(0, id);
        set(1, title);
        set(2, simpleInfo);
        set(3, info);
        set(4, isOnline);
        set(5, createTime);
        set(6, isDelete);
    }
}
