/*
 * This file is generated by jOOQ.
*/
package com.ebupt.admin.database.tables.records;


import com.ebupt.admin.database.tables.OrderRemark;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderRemarkRecord extends UpdatableRecordImpl<OrderRemarkRecord> implements Record6<Integer, Integer, String, Timestamp, Integer, String> {

    private static final long serialVersionUID = -1193209266;

    /**
     * Setter for <code>st.order_remark.id</code>.
     */
    public OrderRemarkRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>st.order_remark.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>st.order_remark.order_id</code>. 订单id
     */
    public OrderRemarkRecord setOrderId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>st.order_remark.order_id</code>. 订单id
     */
    public Integer getOrderId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>st.order_remark.remark</code>. 备注
     */
    public OrderRemarkRecord setRemark(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>st.order_remark.remark</code>. 备注
     */
    public String getRemark() {
        return (String) get(2);
    }

    /**
     * Setter for <code>st.order_remark.create_time</code>. 创建时间
     */
    public OrderRemarkRecord setCreateTime(Timestamp value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>st.order_remark.create_time</code>. 创建时间
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>st.order_remark.status</code>. 0有效 1无效
     */
    public OrderRemarkRecord setStatus(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>st.order_remark.status</code>. 0有效 1无效
     */
    public Integer getStatus() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>st.order_remark.user_account</code>. 操作人
     */
    public OrderRemarkRecord setUserAccount(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>st.order_remark.user_account</code>. 操作人
     */
    public String getUserAccount() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, String, Timestamp, Integer, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, String, Timestamp, Integer, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return OrderRemark.ORDER_REMARK.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return OrderRemark.ORDER_REMARK.ORDER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return OrderRemark.ORDER_REMARK.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return OrderRemark.ORDER_REMARK.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return OrderRemark.ORDER_REMARK.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return OrderRemark.ORDER_REMARK.USER_ACCOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getUserAccount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getUserAccount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRemarkRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRemarkRecord value2(Integer value) {
        setOrderId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRemarkRecord value3(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRemarkRecord value4(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRemarkRecord value5(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRemarkRecord value6(String value) {
        setUserAccount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRemarkRecord values(Integer value1, Integer value2, String value3, Timestamp value4, Integer value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderRemarkRecord
     */
    public OrderRemarkRecord() {
        super(OrderRemark.ORDER_REMARK);
    }

    /**
     * Create a detached, initialised OrderRemarkRecord
     */
    public OrderRemarkRecord(Integer id, Integer orderId, String remark, Timestamp createTime, Integer status, String userAccount) {
        super(OrderRemark.ORDER_REMARK);

        set(0, id);
        set(1, orderId);
        set(2, remark);
        set(3, createTime);
        set(4, status);
        set(5, userAccount);
    }
}
