/*
 * This file is generated by jOOQ.
*/
package com.ebupt.admin.database.tables.records;


import com.ebupt.admin.database.tables.TBackstageMenus;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TBackstageMenusRecord extends UpdatableRecordImpl<TBackstageMenusRecord> implements Record4<Integer, String, Integer, Timestamp> {

    private static final long serialVersionUID = 1716938159;

    /**
     * Setter for <code>st.t_backstage_menus.id</code>.
     */
    public TBackstageMenusRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>st.t_backstage_menus.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>st.t_backstage_menus.menu_name</code>. 菜单名称
     */
    public TBackstageMenusRecord setMenuName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>st.t_backstage_menus.menu_name</code>. 菜单名称
     */
    public String getMenuName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>st.t_backstage_menus.pid</code>. 父ID
     */
    public TBackstageMenusRecord setPid(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>st.t_backstage_menus.pid</code>. 父ID
     */
    public Integer getPid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>st.t_backstage_menus.create_time</code>.
     */
    public TBackstageMenusRecord setCreateTime(Timestamp value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>st.t_backstage_menus.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, Integer, Timestamp> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, Integer, Timestamp> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TBackstageMenus.T_BACKSTAGE_MENUS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TBackstageMenus.T_BACKSTAGE_MENUS.MENU_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TBackstageMenus.T_BACKSTAGE_MENUS.PID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return TBackstageMenus.T_BACKSTAGE_MENUS.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getMenuName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getPid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getMenuName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getPid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBackstageMenusRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBackstageMenusRecord value2(String value) {
        setMenuName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBackstageMenusRecord value3(Integer value) {
        setPid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBackstageMenusRecord value4(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBackstageMenusRecord values(Integer value1, String value2, Integer value3, Timestamp value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TBackstageMenusRecord
     */
    public TBackstageMenusRecord() {
        super(TBackstageMenus.T_BACKSTAGE_MENUS);
    }

    /**
     * Create a detached, initialised TBackstageMenusRecord
     */
    public TBackstageMenusRecord(Integer id, String menuName, Integer pid, Timestamp createTime) {
        super(TBackstageMenus.T_BACKSTAGE_MENUS);

        set(0, id);
        set(1, menuName);
        set(2, pid);
        set(3, createTime);
    }
}
