/*
 * This file is generated by jOOQ.
*/
package com.ebupt.admin.database.tables.records;


import com.ebupt.admin.database.tables.TBackstageUser;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 后台用户表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TBackstageUserRecord extends UpdatableRecordImpl<TBackstageUserRecord> implements Record10<Integer, String, String, String, Integer, String, Timestamp, Timestamp, Integer, String> {

    private static final long serialVersionUID = -599801608;

    /**
     * Setter for <code>st.t_backstage_user.id</code>.
     */
    public TBackstageUserRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>st.t_backstage_user.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>st.t_backstage_user.mailbox</code>. 邮箱
     */
    public TBackstageUserRecord setMailbox(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>st.t_backstage_user.mailbox</code>. 邮箱
     */
    public String getMailbox() {
        return (String) get(1);
    }

    /**
     * Setter for <code>st.t_backstage_user.name</code>. 用户名
     */
    public TBackstageUserRecord setName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>st.t_backstage_user.name</code>. 用户名
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>st.t_backstage_user.password</code>. 密码
     */
    public TBackstageUserRecord setPassword(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>st.t_backstage_user.password</code>. 密码
     */
    public String getPassword() {
        return (String) get(3);
    }

    /**
     * Setter for <code>st.t_backstage_user.jurisdiction</code>. 权限用户类型（1管理员，2运营，3普通）
     */
    public TBackstageUserRecord setJurisdiction(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>st.t_backstage_user.jurisdiction</code>. 权限用户类型（1管理员，2运营，3普通）
     */
    public Integer getJurisdiction() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>st.t_backstage_user.phone</code>. 手机号
     */
    public TBackstageUserRecord setPhone(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>st.t_backstage_user.phone</code>. 手机号
     */
    public String getPhone() {
        return (String) get(5);
    }

    /**
     * Setter for <code>st.t_backstage_user.create_time</code>. 创建时间
     */
    public TBackstageUserRecord setCreateTime(Timestamp value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>st.t_backstage_user.create_time</code>. 创建时间
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>st.t_backstage_user.update_time</code>. 更新时间
     */
    public TBackstageUserRecord setUpdateTime(Timestamp value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>st.t_backstage_user.update_time</code>. 更新时间
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>st.t_backstage_user.status</code>. 状态：1正常 2删除
     */
    public TBackstageUserRecord setStatus(Integer value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>st.t_backstage_user.status</code>. 状态：1正常 2删除
     */
    public Integer getStatus() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>st.t_backstage_user.avatar</code>. 头像
     */
    public TBackstageUserRecord setAvatar(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>st.t_backstage_user.avatar</code>. 头像
     */
    public String getAvatar() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, String, Integer, String, Timestamp, Timestamp, Integer, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, String, Integer, String, Timestamp, Timestamp, Integer, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TBackstageUser.T_BACKSTAGE_USER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TBackstageUser.T_BACKSTAGE_USER.MAILBOX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TBackstageUser.T_BACKSTAGE_USER.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TBackstageUser.T_BACKSTAGE_USER.PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return TBackstageUser.T_BACKSTAGE_USER.JURISDICTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TBackstageUser.T_BACKSTAGE_USER.PHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return TBackstageUser.T_BACKSTAGE_USER.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return TBackstageUser.T_BACKSTAGE_USER.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return TBackstageUser.T_BACKSTAGE_USER.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return TBackstageUser.T_BACKSTAGE_USER.AVATAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getMailbox();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getJurisdiction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getAvatar();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getMailbox();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getJurisdiction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getAvatar();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBackstageUserRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBackstageUserRecord value2(String value) {
        setMailbox(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBackstageUserRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBackstageUserRecord value4(String value) {
        setPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBackstageUserRecord value5(Integer value) {
        setJurisdiction(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBackstageUserRecord value6(String value) {
        setPhone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBackstageUserRecord value7(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBackstageUserRecord value8(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBackstageUserRecord value9(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBackstageUserRecord value10(String value) {
        setAvatar(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBackstageUserRecord values(Integer value1, String value2, String value3, String value4, Integer value5, String value6, Timestamp value7, Timestamp value8, Integer value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TBackstageUserRecord
     */
    public TBackstageUserRecord() {
        super(TBackstageUser.T_BACKSTAGE_USER);
    }

    /**
     * Create a detached, initialised TBackstageUserRecord
     */
    public TBackstageUserRecord(Integer id, String mailbox, String name, String password, Integer jurisdiction, String phone, Timestamp createTime, Timestamp updateTime, Integer status, String avatar) {
        super(TBackstageUser.T_BACKSTAGE_USER);

        set(0, id);
        set(1, mailbox);
        set(2, name);
        set(3, password);
        set(4, jurisdiction);
        set(5, phone);
        set(6, createTime);
        set(7, updateTime);
        set(8, status);
        set(9, avatar);
    }
}
